### ISSUE TITLE
use chrome.tabs.captureVisibleTab for preview

### ISSUE THREAD

**Issue by KrickRay** [k-ivan/visual-bookmarks-chrome#1]

**Comment by k-ivan** [comment]
@KrickRay, насколько я понял в метод  **chrome.tabs.captureVisibleTab** нужно передать id окна, чтобы получить скриншот. Например, при наличии 200 закладок, у нас будут пустые заглушки, пока мы не откроем каждую закладку.

**Comment by KrickRay** [comment]
@k-ivan по дефолту использовать скрин-сервис (можно даже заблюренные скрины), а потом заменять на chrome.tabs.captureVisibleTab, потому что текущие скрины совсем плохо отображают действительность (многие просто страницы авторизации)

**Comment by k-ivan** [comment]
@KrickRay не вижу пока, как это реализовать, дело в том, что я попробовал слушать событие update на текущую вкладку и по нему  в background.js делать скрин, но хранить картинки в base64 в localStorage не вариант, да и куча картинок в base64 значительно затормозит отрисовку страницы закладок, да и место в локальном хранилище хватит картинок на 5-7.

**Comment by KrickRay** [comment]
@k-ivan это не подойдет: https://developer.chrome.com/apps/app_storage?

**Comment by k-ivan** [comment]
FileSystem доступна только в приложениях, js API конечно есть в хроме, но для расширений картинки не удастся хранить в папке самого расширения, необходимо уже переделывать расширение в приложение.

**Comment by k-ivan** [comment]
@KrickRay  решил все-таки попробовать filesystem api для хранения картинок локально, вроде как из хрома это api никуда не денется, не прошло и года ;)
