### ISSUE TITLE
How does https://logo.clearbit.com/[URL] work, I can't figure it out

### ISSUE THREAD

**Issue by meffect** [k-ivan/visual-bookmarks-chrome#10]
### Arbitrary Example Of Problem

I want to use the `github logo` here https://logo.clearbit.com/github.com for a bookmark thumbnail. 

---

#### Issue:

How do I make `bookmark thumbnail` use the logo-image from `https://logo.clearbit.com/github.com`?

##### (1) Refresh Thumbnail

It does a screen grab, which is nice. But I want instead for the software to grab the logo https://logo.clearbit.com/github.com

##### (2) Manual Logo Grab 

1. I bring up the logo in Google Chrome by opening this address `https://logo.clearbit.com/github.com`. 2. I right click and `Save image as...` in Google Chrome. 
3. The dialog box asks me to save a `MS-DOS Application (*.com)` file instead of an image format file. 

#### Final Questions:

1. Does [visual-bookmarks-chrome](https://github.com/k-ivan/visual-bookmarks-chrome) use some intelligent programmatic automatic way to grab the `https://logo.clearbit.com/github.com` logo based on the domain? {And I don't know the process}

2. And/Or If manual logo download `https://logo.clearbit.com/github.com` is required. How do I use this method? Because the Google Chrome `Save image as...` dialog box asks me to save a `MS-DOS Application (*.com)` file instead of an image format file.

**Comment by k-ivan** [comment]
Hi! At the moment, the means of expansion is no way to roll back the thumbnail to the logo

I will try to soon add the ability to reset the thumbnail to the logo in the editing window (just as it is now working with folders)

At the moment, the easiest is the second way. I made a screenshot for clarity. 
1) Select item "all files" in select
2) Enter the extension in the file name at the end of the jpg or png (just in case)
![Untitled](https://user-images.githubusercontent.com/6150895/54283713-a452e480-45af-11e9-8f11-ce12bee635c8.png)

**Comment by meffect** [comment]
Oh ok I see, awesome !
