### ISSUE TITLE
Thumbnails all disappeared

### ISSUE THREAD

**Issue by burt-ie** [k-ivan/visual-bookmarks-chrome#103]
All my thumbnails disappeared and the refresh thumbnail button is greyed out. I can refresh the thumbnails of each individual page but not able to do them all anymore

**Comment by k-ivan** [comment]
Hello!
Need more information to understand what happened.
What did they do, after which they disappeared, what kind of browser, did they clean the browser cache, browser version, extension version. Preferably with screenshots.

**Comment by burt-ie** [comment]
I'm on Microsoft edge Version 107.0.1418.26 (Official build) (64-bit)
Extension version 4.2.1

No reason they disappeared, just opened my browser one day and they were gone.
All my thumbnails have been replaced with the standard site icons. 
I have the button on the top left of the screen to refresh thumbnails, but when I move my mouse over the red circle with a line through it appears and I cannot click the button.
I can however go to each thumbnail and click the drop down menu and refresh each thumbnail individually.

**Comment by k-ivan** [comment]
This is very strange, looks like a local problem. Thumbnails should not disappear for no reason.
But even more surprising is that the button for generating thumbnails is not available. Try resetting the app settings to default.

**Comment by burt-ie** [comment]
Looks like resetting, removing and re-adding the extension has fixed the issue.
Thanks for the help
 :)

**Comment by k-ivan** [comment]
Glad to help, but this is a very strange bug.
