### ISSUE TITLE
Sync Images across devices?

### ISSUE THREAD

**Issue by The1Magoo** [k-ivan/visual-bookmarks-chrome#105]
Just started using this great extension - thank you for all the hard work you've put into it!

I work across multiple devices/Operating systems and although the extension loaded and worked perfectly on my second device it did not appear to take the images I have uploaded across.  Is this expected behaviour?  If so, is there any way to manually copy the images occasionally to keep in sync please?

Cheers,
Dave

**Comment by k-ivan** [comment]
Hello. Thanks for the feedback.

Already thought about this task, but there are nuances.
Unfortunately, at the moment I do not see the possibility of synchronizing images using extensions. Most likely, a dedicated server is needed to synchronize images. But there is another problem, linking images to bookmarks, bookmark IDs when synchronizing on other devices are different, so it’s not clear how to link them to bookmarks after import.

**Comment by k-ivan** [comment]
I think in the near future on this issue it is unlikely that something will become clear. So for now I close this issue.
