### ISSUE TITLE
Background image, local file by file name

### ISSUE THREAD

**Issue by dosoft** [k-ivan/visual-bookmarks-chrome#108]
I would like to get the ability to load the background from the local PC using the file name. So if this file has been changed then it is reloaded.

Currently, it just loads the image once and then it cannot be reloaded automatically.

The scenario is pretty simple: I would like to download an image from Unsplash by the scheduler and use it from the *local* pc to avoid any delays during downloading.

**Comment by k-ivan** [comment]
The extension stores images in the browser's database. Also, the extension does not have full access to your file system (only to its own sandbox)

The Unsplash has a free api(source.unsplash.com), but you have to download an image from the web every time. You can use the link from the unsplash. 

A simple example of referencing a selected collection, each call takes random image from the specified collection
https://source.unsplash.com/collection/:collection_id/2560x1440
Unsplash had a description of the available methods and parameters, the link above is one of the examples.

**Comment by dosoft** [comment]
> The extension stores images in the browser's database. Also, the extension does not have full access to your file system (only to its own sandbox)

Got it.

> The Unsplash has a free API

Yeap, that's how I'm using it now - https://source.unsplash.com/random/3840x2160?nature

Unfortunately, sometimes it works pretty slowly, sometimes even not accessible. In both cases, this extension shows an empty background.

**Comment by k-ivan** [comment]
> Unfortunately, sometimes it works pretty slowly, sometimes even not accessible. In both cases, this extension shows an empty background.

I agree with you, I also use Unsplash as a link. But I don't see any other solution yet.

**Comment by dosoft** [comment]
Cache the previous image and use it after N second(s) or in case if URL is not available at all?

**Comment by k-ivan** [comment]
This seems like a very expensive feature that few people will need, IMHO.

**Comment by k-ivan** [comment]
I think this issue can be closed.
