### ISSUE TITLE
[feature request] make it harder to drop bookmarks in folders

### ISSUE THREAD

**Issue by dvoraking** [k-ivan/visual-bookmarks-chrome#111]
Thanks for the great extension. I've been using it for years. I've also had this problem for years, but now am tech savvy enough to come here and ask for a fix. I have many bookmarks, and when adding a new one and dragging it to where I want to be on the page (usually near the top), I often accidentally drag it into a nearby folder. There's no way to get it out without editing its save location, and that puts it at the bottom again. 

Can you make it harder to drop bookmarks in folders? Preferably, it would be more accurate when dragging and dropping, but I am thinking of practical solutions, like adding an optional delay when holding a bookmark over a folder. Let me set the delay, like with the thumbnail generation delay, so it only puts things in a folder after hovering over the folder for a set amount of time.

Additionally, there is now a large back button in every folder. Why not let me hover bookmarks over that button to send it to the folder above, preferably right next to the folder rather than at the bottom? It might be the best of both worlds, as there may be some who love how quickly bookmarks go in folders when dragged and dropped, or drag many bookmarks at once and don't want the delay. Being able to drag and highlight multiple bookmarks would also be awesome, so you put multiple in a folder at once, and the delay isn't an issue. But I imagine that's a more difficult solution.

**Comment by k-ivan** [comment]
Hello, thanks for the suggestions.

In fact, everything related to drag and drop is a difficult task. Even dragging a bookmark into a folder did not appear immediately. I cannot promise you that everything you described will be implemented, but I will definitely think about these issues.

**Comment by k-ivan** [comment]
Implemented the ability to move selected bookmarks to folders (`SHIFT+click` on bookmark for activation). While without dragging, it is somewhat more difficult to implement it in the current version (maybe later it will be possible to do this). v5.8.0

I think that at this stage it can be considered completed.
