### ISSUE TITLE
[feature request] Sort only bookmarks (rather than folders) by date

### ISSUE THREAD

**Issue by aine9119** [k-ivan/visual-bookmarks-chrome#112]
Thank you for the great extension I've used it for a long time and it's been very useful.

The only issue I've had is that when you sort bookmarks by date, it also sorts folders by date and the folders end up mixed up with the bookmarks and are hard to find and navigate. If there was a way to keep folders pinned to the top (similar to windows explorer) or even better sorted separately using the default sort or by alphabetic order etc that would be very useful. I have no idea how hard that is to implement, but I have noticed a few other bookmark extensions offer this so perhaps not.

Either way thanks for your work.

**Comment by k-ivan** [comment]
Hi! 
Thanks for the idea. I'll think about sorting for folders later and come back with an answer.

**Comment by k-ivan** [comment]
In version 5.4.0 added sorting by type. Will update in the coming days.
