### ISSUE TITLE
After updating to 5.6.0 capture_fill not working

### ISSUE THREAD

**Issue by visbook** [k-ivan/visual-bookmarks-chrome#123]
Hi k-ivan,
My VB got updated just now and I went to refresh all the thumbnails in one of the folders by pressing the top left camera icon like I always do, but nothing happened.
I have closed/ restarted the browser (Brave), and disabled/ enabled VB from the "Extensions" page in Chrome but the camera icon still does nothing.
Any ideas what's gone wrong?

**Comment by k-ivan** [comment]
Hello @visbook!
Yes, sorry, I checked badly, thanks for your attention. I'll fix it soon.

**Comment by visbook** [comment]
Hi k-ivan,
Thanks for promptly fixing the bug.
Have you released v5.6.1 yet though as I can't update?

**Comment by k-ivan** [comment]
Hi visbook!
Yes, now it remains to wait for it to pass the test in the webstore and be allowed.
