### ISSUE TITLE
Requesting restoration of thumbnail service URL option in latest version

### ISSUE THREAD

**Issue by shellaaaron** [k-ivan/visual-bookmarks-chrome#125]
I'm having difficulty adding a service URL on the latest version. In past versions, there was an option to include a thumbnail service URL, which could be left blank for those who didn't want to use it. However, this option is no longer available in recent versions. Can you please restore this option, as it was working well for me before?

_Originally posted by @shellaaaron in https://github.com/k-ivan/visual-bookmarks-chrome/issues/79#issuecomment-1519039223_

**Comment by k-ivan** [comment]
Hello!
I'm sorry, I didn't understand what you mean, could you take a screenshot or describe in more detail?

**Comment by shellaaaron** [comment]
I mean the thumbnail service URL in order to change the URL this is missing in newer version in order to use

**Comment by shellaaaron** [comment]
This was a good option but can't find it in the new version to change the URL here.
/
![Thumbnail service URL](https://user-images.githubusercontent.com/51804000/233841431-7a611ee4-7f7e-49b9-8243-a78a92020533.jpg)

**Comment by k-ivan** [comment]
Yep, got it. I'll see what can be done. The parameter was removed a long time ago.

**Comment by shellaaaron** [comment]
> Yep, got it. I'll see what can be done. The parameter was removed a long time ago.

Thank you, hope it can be restored.

**Comment by k-ivan** [comment]
I'm sorry, but I did not receive a response from you and will close in this case.
