### ISSUE TITLE
'Generating a thumbnail when creating a bookmark' is not triggered when saving new bookmark via chrome default option

### ISSUE THREAD

**Issue by sam-token98** [k-ivan/visual-bookmarks-chrome#128]
Hi,

Truly loving this extension. Thank you for all the hard work.

One issue I've noticed is that when the extension setting 'Generating a thumbnail when creating a bookmark' is on, thumbnails will only be added automatically if the new bookmark is added directly within the extension (by turning on the 'Show column for adding a bookmark') rather than via the default chrome 'Bookmark this tab' option ( such as Ctrl+D or the star in chrome's address bar). Is there any way of fixing this? It would be great if adding a bookmark via the default chrome option triggers a thumbnail to be saved automatically. Without this it causes quite a bit extra work when you working with large volumes of bookmarks.

Thanks for your time!

**Comment by k-ivan** [comment]
Hello. Thanks for the idea!

It doesn't seem hard to add. But there are a few things to check. For example, what happens if you import a large number of bookmarks(via browser settings). When I have time, I will check these points. I'll try to add if there are no nuances.

**Comment by sam-token98** [comment]
Yes, I didn't think of the implications for importing bookmarks via settings. Hopefully can still be worked around. Thanks for having a look!

**Comment by k-ivan** [comment]
Hi.
This feature will appear in the next update (v5.8.0).

**Comment by aine9119** [comment]
Works great, very useful feature. Thanks for all your work!
