### ISSUE TITLE
Weird bug with Ctrl+D? 

### ISSUE THREAD

**Issue by Leifman35** [k-ivan/visual-bookmarks-chrome#130]
Well, unsure how to explain it properly, but ever since the last 1 or 2 updates of Visual bookmarks, i've noticed an annoying bug: I often just ctrl+D on a youtube video page to add it to favorites and instead i see it like "snapshot" in a small square box in the top right from Visual bookmarks doing i don't know what... i have to re-ctrl+D to properly add the bookmark/select where to add it etc'

In the past Ctrl+D didn't trigger anything from Visual bookmark and i have no idea what it does... it seems like a 'snapshot/screenshot' from Visual Bookmark to maybe refresh a site/bookmark? but those random youtube videos are not on my list to refresh the screenshot/image of?

Would love to know how to make it stop doing that.. it never did it before the last 1-2 versions

**Comment by Leifman35** [comment]
Nevermind, it's the "Generating a thumbnail when creating a bookmark" thingy that was causing it. apparently you added that option in the last 1 or 2 updates and set it by default to be on. i disabled it and hopefully this goes away with it.

Not sure why you would add a feature and enable it by default tho? maybe a good idea to just announce that option is now available but not auto-enable it for users of the addon already? just my 2 cents. this can be closed now

**Comment by k-ivan** [comment]
This option has existed for a very long time and has always been enabled,

But you're right in the last update I added auto-generation when creating a bookmark from the browser interface.

After you have turned off the option in the settings, the capture window will no longer pop up.
