### ISSUE TITLE
Thumbnail update does not work on some PCs

### ISSUE THREAD

**Issue by sticman** [k-ivan/visual-bookmarks-chrome#133]
I use your extension as my homepage for Edge on 3 PCs, and it is excellent thank you. On one of them, the thumbnail update button in the top left corner has stopped working. Why did this happen?

Thanks.

Paul

**Comment by k-ivan** [comment]
Hi!

Very strange, try the following in the console(`F12` or `CTRL+SHFT+I`). Copy and paste + ENTER
![unnamed](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/0b4aff56-1a3e-4c43-b96f-cf9a14387975)

```js
localStorage.clear()
```
And refresh page.

**Comment by sticman** [comment]
Hi,

 

Thanks for the response. That allowed me to activate the button, but it still does not work. Now, it opens up another Edge window for each bookmark, but seems to get stuck and does not capture the thumbnail. My other PCs both work, and the second window opens for about 2 seconds and then the thumbnail is captured and updated on the Visual Bookmarks screen. On this one, the second window stays open for about 10 seconds, and the bookmark never gets updated. It must time out, and then try the next one, and that does the same thing.

 

Again, it is only on one PC—the other two work fine. It is the newest PC I have, from 2022. Very strange. Manually refreshing each bookmark still works, it is just the script attached to the automated button that does not.

 

I have been using your extension for several years and it is great. This is the first time I have ever had a problem with it.

 

Thank you and have a good day.

 

Paul

**Comment by k-ivan** [comment]
Very strange. Try checking the permissions for the extension, in order to capture screenshots you need access to all sites.
![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/a2585a62-7cb8-4a14-91c1-4f2dfa358046)

**Comment by k-ivan** [comment]
I close this issue. If you have questions about this topic, just reopen.
