### ISSUE TITLE
New tab/reload blinking

### ISSUE THREAD

**Issue by mario-amazing** [k-ivan/visual-bookmarks-chrome#141]
When I open a new tab or reload it, I faced blinking loading screeen.  When theme is dark -> blink with white and and vice versa.
It's terrible for the eyes at night, could you help to fix it?

https://github.com/k-ivan/visual-bookmarks-chrome/assets/9537753/6024ad20-ff97-4a1e-a240-624045b8f6e7

**Comment by k-ivan** [comment]
Hello Mario!

I don't even know how to help you, I can't reproduce.

Please describe in more detail which browser and version you are using,  and what OS and version, what version of the extension, and when did it appear?

I don't think it's an extension issue.

**Comment by mario-amazing** [comment]
MacOS Ventura 13.4.1 
GoogleChrome(latest) Version 116.0.5845.110 (Official Build) (x86_64)
Bookmark Extension(latest) 5.8.1

This appears when open a new tab(example: pressed command+t)
I have tried another homepage extensions and they have the same blink behaviour(( But maybe you know the Chrome config that can fix it?

**Comment by k-ivan** [comment]
Unfortunately I don't have MacOS to check.

1) Check if the option is enabled in the browser settings - _Use hardware acceleration when available_.  Try enabling or disabling (depending on the selected state).

2) Maybe some other extension is causing this, try turning off all extensions to check.

**Comment by k-ivan** [comment]
After changing parameter 1, restart your browser.

**Comment by mario-amazing** [comment]
Tried, result the same..

**Comment by k-ivan** [comment]
Maybe this thread will help https://www.reddit.com/r/chrome/comments/crxt2o/screen_flickering_on_chrome_mac/

![Screenshot_2023-08-29-23-31-58-11_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/932e95db-379f-4fad-8a55-04a26d7e2035)

**Comment by mario-amazing** [comment]
Yes, the answer above concerns an error when watching a video. But this is when you just open a new tab. It looks like the default white skin is loaded first, and after that the extension is rendered

**Comment by k-ivan** [comment]
Problem may be with the graphics adapter and settings, you tried to do as described in the thread?

**Comment by k-ivan** [comment]
The problem is hardware or with the Chrome browser itself. Try a browser Microsoft Edge for example.

Perhaps this link will be of some use https://www.guidingtech.com/fix-screen-flickering-on-macbook/
