### ISSUE TITLE
Simple yet usefull feature about bookmarks

### ISSUE THREAD

**Issue by bbrother92** [k-ivan/visual-bookmarks-chrome#146]
Было б круто иметь возможно открыть сразу много ссылок в браузере - некий bulk open, очень бы пригодился, если б такой селектор был б. Спасибо за этот плагин, часто пользуюсь.

**Comment by k-ivan** [comment]
Здравствуйте!

Мульти выбор через <kbd>shift+click</kbd> и затем открыть все не подходит как решение?
Или речь не о самих закладках?

**Comment by bbrother92** [comment]
Omg sorry, оно оказывается есть уже. Спасибо!

**Comment by k-ivan** [comment]
Рад помочь!
