### ISSUE TITLE
Горизонтальное центрирование

### ISSUE THREAD

**Issue by ancap-kun** [k-ivan/visual-bookmarks-chrome#147]

**Comment by k-ivan** [comment]
Опишите подробнее о чем речь, иначе не понятно.

**Comment by ancap-kun** [comment]
> Опишите подробнее о чем речь, иначе не понятно.

Есть опция вертикального центрирования, хотелось бы еще горизонтальное чтобы было.

**Comment by k-ivan** [comment]
Честно говоря не вижу смысла в такой опции. Но могу предложить использовать кастомный стиль, если хотите, чтобы контейнер не с закладками не центровался. 
Попробуйте в настройках добавить такой css
```css
:root {
  --container-padding-inline: 50px;
}
.container {
  margin: 0;
}
```
![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/dec65047-be06-4742-ae40-69e71de1033b)

**Comment by ancap-kun** [comment]
Так в том то и дело, что оно сейчас не центрируется (там вместо центрирования отступ), а я хочу, чтобы центрировалось.

**Comment by k-ivan** [comment]
Какое -кол-во закладок вы используйте в одной колонке и какая ширина выбрана в настройках у Вас?

**Comment by k-ivan** [comment]
Возможно кол-во закладок в ряд в настройках и ширина контейнера, а так же размер экрана не позволяют выстроить такое кол-во закладок в один ряд(поэтому активируется центрирование по центру). Попробуйте поиграться с этими настройками. 
![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/af90dd72-6f50-4d34-b747-4632666b974d)


Если речь о чем то другом, то нужен скрин, так как тогда не понимаю в чем вопрос.

**Comment by ancap-kun** [comment]
Все настройки дефолтные. Новые закладки просто добавляются в строку. 



https://github.com/k-ivan/visual-bookmarks-chrome/assets/90708073/1945e102-7e95-4a4e-ad23-9d6fa2312f0a

**Comment by k-ivan** [comment]
В таком случае попробуйте следующий css код добавить в настройки, только имейте ввиду, что данная настройка может влиять на параметр - Число столбцов.

```css
:root {
  --grid-columns: auto-fit !important;
}
```

**Comment by ancap-kun** [comment]
Спасибо! Именно это я и хотел.

**Comment by k-ivan** [comment]
Отлично, в таком случае закрываю.
