### ISSUE TITLE
New quick panel being obscured

### ISSUE THREAD

**Issue by visbook** [k-ivan/visual-bookmarks-chrome#148]
Hi k-ivan

When I select thumbnails with the new Shift key function, a grey box appears in the bottom left corner that shows the web address of the thumbnail I've selected with the mouse, and the box is obscuring the new action shortcut icons.
Is there a way to stop the grey box appearing?
![annoying box](https://github.com/k-ivan/visual-bookmarks-chrome/assets/87253369/2a53e7fc-6ede-47db-8b56-97db0455c4d4)

Can I also use this opportunity to congratulate and thank you (and the team) for turning what was a very good Chrome extension into a superb one- all the newly added features in v5.11 are great and exactly what I needed!

**Comment by k-ivan** [comment]
> Can I also use this opportunity to congratulate and thank you (and the team) for turning what was a very good Chrome extension into a superb one- all the newly added features in v5.11 are great and exactly what I needed!

Thank you, glad you like it )

> When I select thumbnails with the new Shift key function, a grey box appears in the bottom left corner that shows the web address of the thumbnail I've selected with the mouse, and the box is obscuring the new action shortcut icons.
> Is there a way to stop the grey box appearing?

You can try playing with styles
```css
.bookmarks-panel {
  bottom: 30px !important;
}
```
or
```css
.bookmarks-panel {
  direction: rtl;
}
```
Perhaps in the future I will be able to find a better position.

**Comment by visbook** [comment]
> Perhaps in the future I will be able to find a better position.

Could it be moved to the bottom centre or would the grey box just move with it?

**Comment by k-ivan** [comment]
This tooltip is a browser overlay, it has some kind of length limitation, but in theory and on a small screen, it will still reach the panel.

If only the panel is made very small, I need to think about it. I don't know yet.

**Comment by k-ivan** [comment]
The original idea was to fit it into a grid container, but this may not be optimal in all cases.

**Comment by k-ivan** [comment]
> Could it be moved to the bottom centre or would the grey box just move with it?

Try this
```css
.bookmarks-panel {
  max-width: 700px !important;
}
```

**Comment by visbook** [comment]
_Could it be moved to the bottom centre or would the grey box just move with it?_

I meant to say could the new whole Quick Action Panel be moved to the bottom centre (not the grey box).
Also, sorry but I don't know how to enter the code in Brave browser to try your suggestions myself.

**Comment by k-ivan** [comment]
I am glad to help.

**Comment by visbook** [comment]
Hi k-ivan,
I have been using your custom CSS to make the Quick Action Panel centred at the bottom and wondered if there is some additional code that would move the dustbin icon from the left of the folder list box over to the right side.
I'm asking this because when selecting several thumbnails to perform a "open all" or "refresh thumbnail" action, a few times I have accidentally deleted them all instead and lost them all, and so thought it best if the dustbin was in a different area so there'd be less chance of this happening again.

![move icon](https://github.com/k-ivan/visual-bookmarks-chrome/assets/87253369/83d2ca5f-9d58-4e18-8e16-e920bf3ee8dc)

**Comment by k-ivan** [comment]
Hello @visbook 

Try this code
```css
button.bookmarks-panel__action:nth-child(2) {
    order: 1;
}
```

**Comment by visbook** [comment]
Brilliant, thanks k-ivan
