### ISSUE TITLE
Arrange folders via drag&drop like normal thumbnails?

### ISSUE THREAD

**Issue by Ronnuss** [k-ivan/visual-bookmarks-chrome#149]
Is there a way to do that? Would be a nice feature.

**Comment by k-ivan** [comment]
Do you mean sorting?

**Comment by Ronnuss** [comment]
Yes, excuse my phrasing, I mean independent sorting (not alphabetically).

 

Von: Ivan ***@***.***> 
Gesendet: Mittwoch, 8. November 2023 18:57
An: k-ivan/visual-bookmarks-chrome ***@***.***>
Cc: Ronnuss ***@***.***>; Author ***@***.***>
Betreff: Re: [k-ivan/visual-bookmarks-chrome] Arrange folders via drag&drop like normal thumbnails? (Issue #149)

 

Do you mean sorting?

**Comment by k-ivan** [comment]
There is an option to sort by date and by bookmark type, but if the sorting option is enabled in the settings, drag and drop sorting is disabled as it will lead to chaos.

If bookmarks are dragged inside a folder, then in the options you can select that the bookmark is added either at the beginning of the folder or at the end.

But there is no alphabetical sorting, only by date or type (folder at the top or bottom).

**Comment by Ronnuss** [comment]
Hi Ivan,

thank you for this fast response!

As a long time user I had the impression that moving folders was an option some time ago, but obviously  my memory is deceiving me 😊

 

Von: Ivan ***@***.***> 
Gesendet: Mittwoch, 8. November 2023 19:16
An: k-ivan/visual-bookmarks-chrome ***@***.***>
Cc: Ronnuss ***@***.***>; Author ***@***.***>
Betreff: Re: [k-ivan/visual-bookmarks-chrome] Arrange folders via drag&drop like normal thumbnails? (Issue #149)

 

There is an option to sort by date and by bookmark type, but if the sorting option is enabled in the settings, drag and drop sorting is disabled as it will lead to chaos.

If bookmarks are dragged inside a folder, then in the options you can select that the bookmark is added either at the beginning of the folder or at the end.

But there is no alphabetical sorting, only by date or type (folder at the top or bottom).

**Comment by k-ivan** [comment]
I apparently didn’t understand you ), folders can be dragged and dropped like other bookmarks.  Drag and drop should work for folders

**Comment by Ronnuss** [comment]
That’s my problem, I cannot drop between folders, the dragged folder is moved into the next left or right folder. But I just discovered that I can drop any folder to the first or last position without that problem. Takes some time but it’s a working solution for me.

 

Von: Ivan ***@***.***> 
Gesendet: Mittwoch, 8. November 2023 19:36
An: k-ivan/visual-bookmarks-chrome ***@***.***>
Cc: Ronnuss ***@***.***>; Author ***@***.***>
Betreff: Re: [k-ivan/visual-bookmarks-chrome] Arrange folders via drag&drop like normal thumbnails? (Issue #149)

 

I apparently didn’t understand you ), folders can be dragged and dropped like other bookmarks. Drag and drop should work for folders

**Comment by k-ivan** [comment]
The folder has an area, when you hit it, the bookmark is transferred to the folder, so if you only want to sort, try to drag the folder by the bottom, and if there is a folder next to it, drag the captured folder below the drop area, by title level.

PS: This is not at all obvious, but I haven’t figured out how to do it better yet.

**Comment by k-ivan** [comment]
I think with certain settings, it can actually be inconvenient to place a bookmark in a folder, this happens due to the grid being rebuilt at the time of dragging.  I haven't come up with a better solution yet, so there may be some inconvenience.

**Comment by Ronnuss** [comment]
Got it now, thank you for your detailed instructions! 

Your bookmark manager is by far the best manager available, thank you for this brilliant work!

By the way, some pages with lots of items are loading quite slowly. Is there a way to speed it up?

Best greetings

 

Von: Ivan ***@***.***> 
Gesendet: Mittwoch, 8. November 2023 19:59
An: k-ivan/visual-bookmarks-chrome ***@***.***>
Cc: Ronnuss ***@***.***>; Author ***@***.***>
Betreff: Re: [k-ivan/visual-bookmarks-chrome] Arrange folders via drag&drop like normal thumbnails? (Issue #149)

 

The folder has an area, when you hit it, the bookmark is transferred to the folder, so if you only want to sort, try to drag the folder by the bottom, and if there is a folder next to it, drag the captured folder below the drop area, by title level.

PS: This is not at all obvious, but I haven’t figured out how to do it better yet.

**Comment by k-ivan** [comment]
Thank you, glad you like it!

> By the way, some pages with lots of items are loading quite slowly. Is there a way to speed it up?

Please tell me what quantity you are talking about, this may help me for debugging.

Yes, the speed may depend on the number of bookmarks, the browser API itself works quickly, but if you have hundreds or thousands of bookmarks that need to be displayed, then this may take more time and, unfortunately, the display of thumbnails may affect the time, since they are created on the fly.
