### ISSUE TITLE
[Feature Request] Allow resizing of panel images in the settings, and instead of bookmark icon, show preview of websites

### ISSUE THREAD

**Issue by filtration** [k-ivan/visual-bookmarks-chrome#15]
1: Allow resizing of panel images in the settings. Currently, the images are 50% which 'cause it to look like so:

<img src="https://i.imgur.com/q7o21OE.png">

If the option was added to the settings to allow us to change from (50% to 100%) it would look like so:

<img src="https://i.imgur.com/3cxGaxu.png">

Which I think looks much better to be honest.

2: Add anoption to preview the current bookmarks in folders,  currently it looks like so:

<img src="https://i.imgur.com/SIfDz7G.png">

But if the option was added to preview the current bookmarks (or atleast 4) it would look like so:

<img src="https://i.imgur.com/Brbkeey.png">

**Comment by k-ivan** [comment]
Hey @filtration . Thanks for the suggestions.

1. I would not like to add functionality for such trifles, but I understand your desire to customize the theme for yourself. I would like to offer an alternative, in my opinion more powerful.
The ability to add your own styles in the settings. This will require some knowledge of the style sheets, but it will provide more opportunities for customization. What do you think?

2. The idea is interesting, I will definitely consider it, but I can not guarantee that this functionality will appear.

**Comment by filtration** [comment]
> Hey @filtration . Thanks for the suggestions.
> 
> 1. I would not like to add functionality for such trifles, but I understand your desire to customize the theme for yourself. I would like to offer an alternative, in my opinion more powerful.
>    The ability to add your own styles in the settings. This will require some knowledge of the style sheets, but it will provide more opportunities for customization. What do you think?

Sounds good to me.

> 2. The idea is interesting, I will definitely consider it, but I can not guarantee that this functionality will appear.

Just thought I'd recomend :)

**Comment by k-ivan** [comment]
Excellent. then I’ll add the ability to override styles as soon as possible.

**Comment by k-ivan** [comment]
Hey @filtration. Forgot to notify. The field for custom styles on the advanced tab in the settings, starting with version 3.5.1.
![Untitled](https://user-images.githubusercontent.com/6150895/59143638-6f4f0600-89d5-11e9-84bd-118b4414032c.png)

**Comment by shellaaaron** [comment]
Actually good idea if that possible.

not everyone knows what to write on custom CSS.

**Comment by shellaaaron** [comment]
> If the option was added to the settings to allow us to change from (50% to 100%) it would look like so:

But how to add this to custom CSS from 50% to 100% ?

**Comment by k-ivan** [comment]
> Actually good idea if that possible.
> 
> but not everyone knows what to write on custom CSS so you can write what to write in custom CSS for example to customize the size of thumbnails.

I agree with you. But visual things, such as font size, rounding up of form fields and buttons, or changing the size of background images, seems to me to be overload.

**Comment by k-ivan** [comment]
> > If the option was added to the settings to allow us to change from (50% to 100%) it would look like so:
> 
> But how to add this to custom CSS from 50% to 100% ?

@shellaaaron You can use custom variables (this is convenient if you need to apply your value in several elements)
```css
:root {
  --custom-bg-size: 100%;
  /* your other possible variables */
}
.bookmark__img--folder {
  background-size: var(--custom-bg-size);
}
.another-exampe-selector {
  background-size: var(--custom-bg-size);
}
```
or change it directly at the element
```css
.bookmark__img--folder {
  background-size: 100%;
}
```

**Comment by shellaaaron** [comment]
not sure why that does not work with me?

I've set the thumbnail service to https://api.miniature.io/?width=1199&height=800&url=[URL]

It shows small size, that CSS override does not help me make it full size 100% and folders do not have thumbnails as well.

Can you help?

**Comment by k-ivan** [comment]
@shellaaaron yes, try like this
```css
.bookmark__img--external {
    background-size: cover;
    background-position: top center;
}
```
This selector `.bookmark__img--external` is responsible for images from an external thumbnail resource.

**Comment by shellaaaron** [comment]
@k-ivan How to make folders like @filtration mention with CSS? if the folder has thumbnails and now showing in folder icon.

I am using all CSS override as you instructed, I am not a CSS expert.

`:root {
  --custom-bg-size: 100%;
  /* not sure what to put here */
}
.bookmark__img--folder {
  background-size: var(--custom-bg-size);
}
.another-exampe-selector {
  background-size: var(--custom-bg-size);
}

.bookmark__img--folder {
  background-size: 100%;
}

.bookmark__img--external {
    background-size: cover;
    background-position: top center;
}`

**Comment by k-ivan** [comment]
@shellaaaron There is no such functionality, you can not see a preview of the sites that are inside the folder.

**Comment by shellaaaron** [comment]
> But if the option was added to preview the current bookmarks (or at least 4) it would look like so:
> 
> ![](https://camo.githubusercontent.com/75cf0bae4fe325b52c46e1da8d83aa919fa56754/68747470733a2f2f692e696d6775722e636f6d2f4272626b6565792e706e67)

So that's actually not possible via CSS?

**Comment by k-ivan** [comment]
Currently no

**Comment by k-ivan** [comment]
Hey @filtration @shellaaaron 
In version 3.6.0 i tried to add thumbnails of random sites from a folder instead of a folder icon and see what happens.
![Annotation 2019-07-21 165137](https://user-images.githubusercontent.com/6150895/61592223-06180080-abd9-11e9-9a20-03bf17d3a302.png)
default setting is disabled
![Annotation 2019-07-21 165625](https://user-images.githubusercontent.com/6150895/61592224-06180080-abd9-11e9-868f-1ffd0a63bad7.png)
