### ISSUE TITLE
When I create a new book mark a window pops up for 2 second

### ISSUE THREAD

**Issue by theigloo** [k-ivan/visual-bookmarks-chrome#153]
Hi

When I am on a webpage and click the star icon in Google Chrome address bar to create a new bookmak, for a brief moment the page I am bookmarking appears in a browser popup window the goes away.

Only happens when this extension is enabled

https://youtu.be/3wXifKc5qfI?si=LK6UD3GnCfBK23cK

thanks

**Comment by k-ivan** [comment]
Hello!

This is normal behavior.  A popup is necessary to generate a site thumbnail.  

Previously, it could be hidden outside the visible part, but now the browser's security policy requires that the screen capture be visible to the user.

If you don't like it, you can disable this feature in the extension settings.

**Comment by theigloo** [comment]
Ah I see, thanks

**Comment by k-ivan** [comment]
I am glad to help.
