### ISSUE TITLE
Multiple folders open at the same time

### ISSUE THREAD

**Issue by wiha99** [k-ivan/visual-bookmarks-chrome#155]
It would be incredibly useful to be able to customize the page to have multiple folders open. To be able to set a custom interface of three folders in different places to always display in a customized way. Essentially just having the ability to have multiple folders open at the same time displaying them side by side.

**Comment by k-ivan** [comment]
Hello!
I’m not sure that I understood you correctly, if you mean that the list would display the contents of several folders at once, then purely in theory this is possible, but not in the case of the current extension architecture, this is a completely different application architecture. The current implementation is in no way compatible with this request.

**Comment by wiha99** [comment]
Ok, yes that was what I menant

**Comment by k-ivan** [comment]
Sorry, but this option is not compatible with the current concept.
