### ISSUE TITLE
Drag and Drop not working now in Brave Browser

### ISSUE THREAD

**Issue by visbook** [k-ivan/visual-bookmarks-chrome#157]
Hi k-ivan, I hope you are well.

I use Brave Browser and for some reason the drag-and-drop function in VB has stopped working; when I try to move a thumbnail VB is displaying a red “no entry” circle.
My VB settings are to allow drag and drop and I’ve tried different settings but I can’t get the drag-n-drop to work.

I’ve also tried disabling/ enabling VB, disabling all my other 3rd party extensions, I uninstalled/ reinstalled VB, shutdown/ restarted the computer.
After more checking it may have something to do with Brave being automatically updated yesterday to version 1.62.153.

I don’t know if everyone is having this issue and if you can replicate in on Brave yourself to see if it is a user wide issue or just affecting me.
**Note**: On another workstation that still has Brave v1.61 installed, VB's drag-and-drop works fine.

![DSCF6768](https://github.com/k-ivan/visual-bookmarks-chrome/assets/87253369/66fc4bd8-d3a3-4a8b-b0e0-a79ac12a4a2d)

**Comment by k-ivan** [comment]
Hello, I tried to install the browser, I don’t see any problems, it looks like it’s a local problem.

Try clearing local storage for the extension
![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/f4578dda-3294-4a58-b3f8-6aa8577bafd0)

**Comment by visbook** [comment]
Will clearing the local storage delete all of the thumbnails?

**Comment by k-ivan** [comment]
No, images are saved in the IndexDB.

**Comment by visbook** [comment]
Cleared the entry, restarted the browser, also changed VB D-n-D slider but no change.

**Comment by k-ivan** [comment]
Check if you have enabled the sorting settings when displaying, these settings are incompatible with dragging.

![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/2afc4de1-f7ce-42fe-b0de-85a7b54767df)

**Comment by visbook** [comment]
Only D&D is enabled and my settings are the same as your clip,

**Comment by k-ivan** [comment]
Try resetting the extension settings to the default (if synchronization is enabled, then these settings too).

**Comment by visbook** [comment]
I had to do a Brave reinstall to get it working again, but have lost my 3,000+ thumbnails; however before I did the reinstall I saved my Brave User Data folder from Windows>Users>AppData>Local> BraveSoftware>Brave-Browser.

Rather than having to update all the thumbnails in VB again which will take a very long time, can I just copy and paste the .blob folder from my saved IndexedDB folder into the same current AppData>Brave-Browser folder?
![IndexDB](https://github.com/k-ivan/visual-bookmarks-chrome/assets/87253369/60ac6270-8c94-48a4-9d3b-73e6e84eb22f)

**Comment by k-ivan** [comment]
Of course you can copy it, but I don’t know whether it will help or not. I haven’t been interested in this issue for a very long time. In theory it should help, but I don’t know if it will help with indexDB data.

**Comment by visbook** [comment]
While I’ve got your attention k-ivan, when I was altering the VB settings to try to get the drag and drop to work, I saw a few settings and would be grateful if you can explain what they change and actually do, I moved the sliders but couldn’t see what difference they made.

1)	Include a panel with services
2)	Show in context menu
3)	Enable Synchronisation
4)	Delete Synchronisation Data from Server

**Comment by k-ivan** [comment]
When I'm at the computer I'll take screenshots.

**Comment by k-ivan** [comment]
1)
![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/808c3039-7801-4902-bc24-9c52e11956b1)

2)
![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/4aa7b341-ce58-4d40-be28-95044c429d39)

3) Application settings will be synchronized in your browser account between devices
4) Reset settings from step 3, that is, the synchronized data will be reset

3, 4 - relate only to extension settings, not images

**Comment by visbook** [comment]
Thanks for taking the time for showing me what these options do and am now up to speed with all the VB options (I think)-
There is just one more question I forgot ask previously-

When you instruct VB to add a bookmark of a webpage, VB opens a large second window in the bottom right of the monitor, which it needs in order to take a screenshot and create the webpage thumbnail.
I use 3 monitors and usually have the browser open on one of the side monitors as I need to carry on using other programs on my main monitor and these other programs need to be always totally visible and accessible.

Presently when using VB, it doesn't matter on which of the monitors you have your Browser app open, the VB pop-up screen always displays in the lower right of the middle monitor which blocks access to the other program screen.
Therefore, is there some custom code/ custom coordinates or another way to force the VB window to pop-up on one of the side monitors, ideally in the top left corner?
It would be even better if I had total control of where the VB pop-up window appears and the ability to put it wherever I like.

It would make it so easy if you could move the VB pop-up window by doing the following-
In General options, move the _"Delay before creating a thumbnail"_ slider to 10+ seconds, right click on a webpage and tell VB to add the page to your bookmarks, then when the VB pop-up window appears you have up to10 seconds to drag the pop-up window to a new permanent position where all VB's future pop-up windows will appear.

**Comment by k-ivan** [comment]
The browser, or rather the system, decides on which monitor to display the window, perhaps the user can control this.

Asking at the time of creating a screenshot is not correct, since the code that generates the screenshot runs in the background, it can be launched when the tab itself is not even open, in addition, it can trigger the generation of several thumbnails.  That is, this is completely wrong, and it is not possible to implement it normally and clearly.

The window is given coordinates, but I think it would be wrong to enter additional settings.  In theory, it would be possible to adjust the screen edge selection, but there is a lot of work, and no one will use it. So I’m not even ready to add this option yet.
