### ISSUE TITLE
Update a local bookmarks directory directly from a JSON source

### ISSUE THREAD

**Issue by webresurs** [k-ivan/visual-bookmarks-chrome#158]
interesting synchronization from a file like this

#https://chromewebstore.google.com/detail/json-bookmarks/nhcplcjcgpjimjnohoijcjglolbdhahg

**Comment by k-ivan** [comment]
To be honest, I don't understand what you mean.

**Comment by webresurs** [comment]
Еще добавить синхронизацию закладок из локальной сети

**Comment by k-ivan** [comment]
Все еще не совсем понимаю, Вы хотите иметь возможность экспортировать бэкап файл с закладками, чтобы перенести егд на другое устройство?

**Comment by webresurs** [comment]
Да, без сторонних синхронизаций и манипуляций с выбором и загрузкой файла
Открыл браузер, там загрузились новые закладки

**Comment by k-ivan** [comment]
В этом нет необходимости, весь функционал уже реализован самими браузерами, все они умеют и экспортировать и импортировать. А поскольку мое расширение работает с закладками браузера, то нет смысла повторяться данным функционалом.
