### ISSUE TITLE
Remove URL in address bar

### ISSUE THREAD

**Issue by Meonthb** [k-ivan/visual-bookmarks-chrome#159]
When open the new tab, the extension URL will display in the address bar, can you remove it?
![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/60881723/fa0186f0-7589-4fd3-b3cf-acd6022044b9)

**Comment by k-ivan** [comment]
you have the option enabled?
![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/7141d7b1-7918-4e6d-9437-a971e350a518)

**Comment by Meonthb** [comment]
Thank you! yes, I find the URL disappear after disabling it.
