### ISSUE TITLE
Can't get 'select a range of bookmarks with SHIFT + CTRL + CLICK' shortcut to work

### ISSUE THREAD

**Issue by samubinas** [k-ivan/visual-bookmarks-chrome#160]
Maybe I have a wrong idea on how this should be operating, but at the moment there just isn't a way to get this working (clicking on individual bookmarks/folders one by one still works though).

Using Chrome Version 123.0.6312.87 (Official Build) (x86_64), on MacOS.

**Comment by k-ivan** [comment]
I didn’t understand you, is this functionality not working for you?

**Comment by samubinas** [comment]
> working



> I didn’t understand you, is this functionality not working for you?

It's not working!

**Comment by k-ivan** [comment]
I checked it myself, the range selection works

https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/b703b524-d46a-4e0e-b359-57eb4d2a1c5d

**Comment by k-ivan** [comment]
Very strange.  Unfortunately, I don’t have a Mac OS, I’ll try to find a way to check if possible.

**Comment by samubinas** [comment]
Sounds good!

**Comment by k-ivan** [comment]
I made a small fix for MacOS v5.12.5, please try it. I checked it on the [browserstack](https://www.browserstack.com/) platform and it works.

**Comment by samubinas** [comment]
It works!! THANK YOU!!!

**Comment by k-ivan** [comment]
Glad to hear.
