### ISSUE TITLE
Change behaviour: click on extension icon

### ISSUE THREAD

**Issue by sevachka** [k-ivan/visual-bookmarks-chrome#163]
Privet,

I would like to see a change in behaviour: if you click on the extension-icon, the visual-bookmarks-page should open in the same tab instead a new one.

cheers

**Comment by k-ivan** [comment]
Hello! )
I'll see. I'll give an answer a little later.

**Comment by sevachka** [comment]
I found a workaround: I have added the homepage-icon to the bar. Clicking on it opens the visual-bookmarks-page.

**Comment by k-ivan** [comment]
A little later, when I have time, I’ll add an option when you click on the icon, it looks like there shouldn’t be any problems.

**Comment by k-ivan** [comment]
@sevachka Hi!

Since you managed to find a solution, may I skip adding this option? It wouldn't cause any problems, but to be honest, I don't like the code required to implement it.

**Comment by tipodanet** [comment]
> A little later, when I have time, I’ll add an option when you click on the icon, it looks like there shouldn’t be any problems.

but only as an option. There are people who only need a new page. For example, for comparison with the previous page

**Comment by tipodanet** [comment]
И вообще , Sevachka мог бы to Ivan  писать и по-нашему

**Comment by k-ivan** [comment]
I'll close this without adding the functionality due to the reason I described above, as I didn't receive a response and it may no longer be relevant. @sevachka , if this is still relevant for you, please reopen this issue.
