### ISSUE TITLE
[Feature request] Add option to refresh all thumbnails at once in a folder or on the parent folder

### ISSUE THREAD

**Issue by shellaaaron** [k-ivan/visual-bookmarks-chrome#17]
[Feature request] Add option to refresh all thumbnails at once in a folder or on the parent folder at once, instead of refresh each one alone.

**Comment by k-ivan** [comment]
Hey @shellaaaron! 
This option is already there. You need to make sure that the option to display the button on the bookmarks page is enabled. After enabling this setting, a button will appear to generate thumbnails for the current folder.
![Untitled](https://user-images.githubusercontent.com/6150895/59972433-ce954480-9597-11e9-9ea2-0aa5e2fb4445.png)
![Untitled1](https://user-images.githubusercontent.com/6150895/59972434-ce954480-9597-11e9-99cc-93b5b2aadaf6.png)

**Comment by shellaaaron** [comment]
Yes, I was asking to update all. I already select that but it's not showing in folders.

Using Version 3.5.3

**Comment by shellaaaron** [comment]
I'm not certain why, but a really great feature was completely removed.

**Comment by shellaaaron** [comment]
I'm not certain why, but a really great feature was completely removed.

**Comment by k-ivan** [comment]
> @k-ivan  I'm not certain why, but a really great feature was completely removed.
> 

Hello @shellaaaron !
I did not remove this option, it works, can you clarify why you decided that it was removed?
