### ISSUE TITLE
Show the Favicon next to the title does not hide filder icons

### ISSUE THREAD

**Issue by wnagrodzki** [k-ivan/visual-bookmarks-chrome#176]
It would be great if "Show the Favicon next to the title" option removed folder icons when disabled.

<img width="1027" alt="Screenshot 2024-09-07 at 09 46 34" src="https://github.com/user-attachments/assets/ffa8acf8-b921-4dfc-a587-6afa5a8cdf30">

**Comment by k-ivan** [comment]
Hi!

You're right, I somehow missed that. I'll fix this behavior in the next update.

**Comment by k-ivan** [comment]
Done, updated to version 6.2.2.
