### ISSUE TITLE
Disturbing line

### ISSUE THREAD

**Issue by shelmor123** [k-ivan/visual-bookmarks-chrome#18]
Is there any way to disable the border line? It's obfuscating my picture. Here are the screenshots for dark and white mode.
![WqG2w2O](https://user-images.githubusercontent.com/52059245/60990315-d0f5ed80-a350-11e9-88c4-56b014a3cef7.jpg)

![pJacpfF](https://user-images.githubusercontent.com/52059245/60990307-cd626680-a350-11e9-83c2-4b3c1e8ceb05.jpg)

**Comment by k-ivan** [comment]
Hi, I will try to resolve this issue as soon as possible.

**Comment by k-ivan** [comment]
@shelmor123 Please check in version 3.5.4

**Comment by shelmor123** [comment]
Thank you, it's perfect now.
