### ISSUE TITLE
Upload from clipboard

### ISSUE THREAD

**Issue by k-ivan** [k-ivan/visual-bookmarks-chrome#180]
When you press right click on tiles you can "Upload from computer", but it would be more useful to paste image from clipboard "Upload from clipboard", after you take a screenshot or copy image from another page.

**Comment by wnagrodzki** [comment]
@k-ivan Hi, would it be possible to make clipboardRead an optional permission? Developer can always audit the code, but regular user however would feel safer having ability to disable it.

**Comment by k-ivan** [comment]
Hi @wnagrodzki !

Unfortunately, in Firefox, it doesn't work without this permission, and making it optional isn't possible. Chromium-based browsers can work without it and request the permission optionally, but for some reason, Firefox only works if it's added as mandatory.

**Comment by k-ivan** [comment]
Actually, this isn't the most concerning permission. For instance, access to all websites (for creating website thumbnails) already provides far more capabilities, making this permission seem insignificant in comparison.

**Comment by wnagrodzki** [comment]
@k-ivan Thank you for making permissions optional

**Comment by k-ivan** [comment]
You're welcome! I’m not even sure why I initially thought it was mandatory, I jumped to conclusions. I should’ve checked the documentation.
