### ISSUE TITLE
Не запоминает состояние

### ISSUE THREAD

**Issue by tipodanet** [k-ivan/visual-bookmarks-chrome#183]
Расширение стартует всегда с главной верхней папки .
Это так задумано ?
Если есть выбор в Селекторе, он должен запоминать состояние.

**Comment by k-ivan** [comment]
Так и задумано, папку с которой стартует расширение, можно поменять в настройках. Не уверен, что выбор нужно сохранять из селекта. Тут нужно узнать больше мнений по этому вопросу, насколько оно необходимо.

**Comment by tipodanet** [comment]
Да,  действительно , из настроек запоминает. Мне этого достаточно. Я не выхожу из папки "Express Panel". Я даже не знаю, откуда она взялась. Я точно ее не создавал. И в Chrome тоже. В Vivaldi есть такая папка. Но как она оказалась здесь ???
 Я пока с трудом понимаю, откуда берутся мои Закладки :)

**Comment by k-ivan** [comment]
> Да,  действительно , из настроек запоминает. Мне этого достаточно. Я не выхожу из папки "Express Panel". Я даже не знаю, откуда она взялась. Я точно ее не создавал. И в Chrome тоже. В Vivaldi есть такая папка. Но как она оказалась здесь ???
>  Я пока с трудом понимаю, откуда берутся мои Закладки :)  

У всех браузеров в закладках есть папки по умолчанию, которые есть изначально, называться могут по разному в зависимости от вендора.

**Comment by tipodanet** [comment]
По поводу
> Не уверен, что выбор нужно сохранять из селекта.
проблема известная . Возникает везде, где есть выбор . Там же есть и "тысяча мнений".
Разработчики выбор не сохраняют, т. к. это default . Им некогда обращать внимание на мелочи, оставляют "как есть".
Потом юзеры начинают наполнять форумы "Сделайте запоминание". А некоторые разрабы (а скорее , представители по PR, которые С++ от English не отличают. Разрабы свои же форумы редко читают) могут нагло утверждать "вас тут проголосовало 10 человек, а у нас 2,5 миллиона благодарных домохозяек, Они скочали и их все устраивает."
Такая логика.  И за это они получают ЗП, за то что опускают бедных юзеров-бесплатных тестеров. И за то, что не доносят мнение юзеров до разрабов. Просто за , то  что он знает русский. Это так устроена в Вивальди русская ветка форума. 
Спорить "надо или нет" можно бесконечно.

Мое одинокое мнение: 
Юзер на этой неделе сосредоточен на "Кино". Изучает обзоры, собирает Закладки, сваливает их в папку "Кино". Потом он смотрит фильмы, чистит папку "Кино". Т.е в течение этой недели он не выходит из папки "Кино". А комп выключает 7 раз в неделю. Ему нужно Сохранение последней папки. 
На след неделе он занят темой "Soundttrack". Все тоже самое.

Скорее всего, папки "Кино" и "Soundttrack" рядом. Уже ближе, чем из самого корня. 
Лично мне однозначно надо Сохранение позиции. 

и как всегда я обеими руками за галку "Сохранение да/нет" , устраивающую интересы всех.

**Comment by k-ivan** [comment]
Сделать это не долго, но это поведение не совсем верное. Смотрите на это как на сайт,    если вы заходите на главную, Вы всегда видите главную, если Вы переходите с главной на другую страницу, то при следующем заходе на главную,  Вы будите на главной. Здесь точно такой же принцип.
Я считаю не логичным его ломать.

Но если, будут подобные запросы ещё, то без проблем, но, на данный момент Ваш запрос единственный за 8 лет существования расширения.

**Comment by tipodanet** [comment]
если будет Сохранеие позиции, Те юзеры, кому это надо , смогут сохранить "Вход на главную". 
Иван , не будьте , как Шпанков с его "2,5 миллиона все устраивает". Напомню , у Вас ссылка на этот Githab появилась на странице расширения на прошлой неделе. И желающих заходить на какие-то форумы, писать предложения примерно 0,000001 % . Большинство не будут это делать даже за деньги.

**Comment by k-ivan** [comment]
Ссылка на гитхаб уже несколько лет есть в описании. Кому что-то нужно либо пишут здесь, либо на почту. 

Если никто ни о чем не просит, то опции я добавляю те, что считаю нужными.

Я уже ответил в предыдущем комментарии, что это не правильное поведение с точки зрения логики, но если помимо вашего запроса появятся ещё, то добавим это.
Сейчас же это просто не логичное поведение, так как селект это не настройка, это на данный момент альтернатива меню.

**Comment by tipodanet** [comment]
Есть стратегия "Sleep Mode". И я часто не выключаю комп полностью. Открыты недописанные тексты, браузеры и окна .
Один баузер открыт с 10 вкладками несмотренными, в другом браузере фильм на паузе, ChatGPT с историей и незаконченными ответами.
В трее висит "Ashampoon Cleaner".  Только я окно закрою, он сразу очищает его кеш. Нет необходимости перегружать комп даже ради чистой загрузки.
На форумах тоже часто встречаю "я месяцами комп не выключаю, только в спящий режим'.

Как можно это все закрыть ? И потом зайти на чистый рабочий стол, и начинать сначала, вспоминать где все застряло ?
Это и есть стратегия поведения, противоположная  "зайти на главную"

**Comment by k-ivan** [comment]
То что Вы описали, прекрасно работает и сейчас, после того как Вы перейдете в папку, вы можете закрыть браузер и открыв его снова, у Вас откроется та папка, на который вы были перед закрытием браузера. Более того, если вы перезагрузите компьютер не закрывая браузер, после перезагрузки, запустив браузер, Вы также окажетесь в той папке, которая была открыта до перезагрузки. Нет никакой проблемы, просто не закрывайте эту вкладку и ее состояние будет сохраняться даже после перезагрузок.

**Comment by tipodanet** [comment]
и все-таки было бы лучше иметь галку в настройках.  Тем более, там уже есть место для этого -- "Отображать папку по умолчанию" и рядом галка "Запоминать последнюю папку". Каждый сам выберет себе стратегию для стартового открытия.

**Comment by k-ivan** [comment]
Повторюсь селектор это альтернатива меню, возможно в будущем его и заменит меню. Меню не может и не должно менять главную страницу входа, это как с сайтом, такое же поведение.

**Comment by tipodanet** [comment]
Я про то , что повторить такое меню -- много работы. Даже если его упростить вдвое. И я это понимаю, и не требую . Половинчатые решения без поиска, фильтрации -- не юзабельны.

**Comment by tipodanet** [comment]
Иван, вы как-то говорили  , что в фоне можно запустить скрипты , например от THREE. 
Вот тогда у вас будет юзеров сразу + 1000000.  Надо признать, большинству важен дизайн, а не поиски, селекты, менюшки.

**Comment by k-ivan** [comment]
Посмотрим.
