### ISSUE TITLE
Корзина

### ISSUE THREAD

**Issue by tipodanet** [k-ivan/visual-bookmarks-chrome#187]
Такое уже есть. Полезная вещь. Скрытая папка с именем "Корзина".
можно ее разместить за ПЛЮСом,  с  :hover { opacity: 1 } 
вот для таких случаев "случайно удалил".
Желательно, чтобы Папки и Закладки не теряли структуру. Сортировка по дате удаления. Срок хранения : 1 месяц.[ Она нужна редко, сразу после испуга, залезть и восстановить.](https://github.com/k-ivan/visual-bookmarks-chrome/issues/186#:~:text=%D0%9F%D0%BE%D0%BA%D0%B0%20%D1%8F%20%D0%B4%D1%83%D0%BC%D0%B0%D0%BB%2C%20%D1%87%D1%82%D0%BE%20%D1%8D%D1%82%D0%BE%20%D0%B7%D0%B0%20TIPS%20%D0%BD%D0%B0%20%D0%BF%D1%83%D1%81%D1%82%D0%BE%D0%BC%20%D0%BC%D0%B5%D1%81%D1%82%D0%B5%20%D1%82%D0%B0%D0%BA%D0%B0%D1%8F%20%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%BD%D0%B0%D1%8F%2C%20%D1%8F%20%D0%B5%D0%B5%20%D1%83%D0%B4%D0%B0%D0%BB%D0%B8%D0%BB.)

**Comment by tipodanet** [comment]
Github не поддерживает "ссылку на выделенный текст". Это же общее изобретение, а не конкретного браузера. Текст должен быть выделен. Github что-то намутил и деградирует.

**Comment by k-ivan** [comment]
Такого в планах нет и не планируется. Создавать ради корзины еще одну псевдобазу закладок точно нет.

Но я подумаю над добавлением таймера отмены при удалении закладки(таймер на несколько секунд), чтобы пользователь мог отменить удаление закладки(как альтернатива).

**Comment by tipodanet** [comment]
Для образца, что кому-то это все-таки надо.
![image](https://github.com/user-attachments/assets/aac8e004-45ae-4a78-8890-8ef25625355c)

**Comment by k-ivan** [comment]
Я не хочу создавать ещё какое-то хранилище, чтобы их там складировать и писать ещё кучу бизнес логики ради корзины. По крайней мере в ближайшем будущем таких планов нет. Если будут массовые запросы, тогда возможно.

**Comment by tipodanet** [comment]
а какая там  " бизнес логики" ? Это такая же папка. В данном решении видимая, всегда свернута. Поведение ничем не отличается от других папок. 
На нее сортировка не действует  -- всегда " от последней удаленной вниз"

**Comment by tipodanet** [comment]
Насколько я знаю  , недавно Chromium расширил действие Истории / yt помню, что-то они там дополнили , хранение по умолчанию полгода. Значит, кому-то это надо  -- копаться в истории
