### ISSUE TITLE
Thumbnails not showing on multiple folders

### ISSUE THREAD

**Issue by Shae-Clark** [k-ivan/visual-bookmarks-chrome#192]
Site thumbnails aren't showing on a number of my folders. This started about a month to two months ago but I figured it was a glitch & it would get fixed but it still hasn't.

The ones that are marked are folders that aren't showing the thumbnails. 
![11 24 24 0 01AM](https://github.com/user-attachments/assets/d10a69d7-d7f9-4f17-bd37-dc58ffdb860c)

**Comment by k-ivan** [comment]
Hello!

Please export the settings and upload them here or send them to me by email. The thing is, I can't reproduce this behavior on my side.
I would be grateful.

![image](https://github.com/user-attachments/assets/8b320f12-1eee-4c53-afc8-e0321e5ed2e4)

**Comment by k-ivan** [comment]
Thank you. I checked and thought it might be something in the settings, but no, they were successfully exported. It’s still unclear.

Since the cause is not clear, try resetting the settings to default. If that doesn't help, reset the synchronization settings as well.

**Comment by k-ivan** [comment]
I couldn't reproduce the issue, it resolved itself on its own.
