### ISSUE TITLE
Firefox Mobile / Android

### ISSUE THREAD

**Issue by C-O-D** [k-ivan/visual-bookmarks-chrome#194]
Hi @k-ivan,

first of all, thank you very much for porting this great extension to Firefox. In the desktop browser everything works great so far but in the mobile version I can't open the addon at all. Do you think you can do something about this?

Best regards

**Comment by k-ivan** [comment]
Hi @C-O-D !

Thank you for the kind words! 😊

When publishing an extension, I can specify that it is available for Android, as far as I remember. I never check that box. For this reason, the "Add to Firefox" button is disabled on mobile.

To be honest, I doubt the extension will work in mobile Firefox. Since the extension needs to be able to override the start page, I believe mobile browsers won’t allow this functionality.

**Comment by C-O-D** [comment]
Thank you for your prompt reply!
In Firefox forks such as Iceaven or Fennec (after entering Developer Mode), you can specify your own add-on collections and thus make it possible to load add-ons that are not regularly permitted. You can also install XPI files manually from local storage, which also works in Firefox nightly.
In this respect, it was no big problem to install Visual Bookmarks - my problem is that when I call it up in the menu, nothing happens 🥴
It would be just too nice if I could load it in Firefox mobile like in the mobile Chrome browsers...

**Comment by C-O-D** [comment]
Oh yes, then you can put a shortcut on the start page for the addon which is at least a compromise you can live with 😉

**Comment by k-ivan** [comment]
> then you can put a shortcut on the start page for the addon which is at least a compromise you can live with 

To be honest, I didn't understand this part )

**Comment by C-O-D** [comment]
> > then you can put a shortcut on the start page for the addon which is at least a compromise you can live with
> 
> To be honest, I didn't understand this part )

In contrast to Chrome, you can create bookmarks in Firefox that lead to add-ons. In this respect, you can simply create a link to VB on Firefox's start page and you are then just one click away. As I said, it's not ideal but it's better than nothing...

**Comment by k-ivan** [comment]
Do you want me to add something, or are you just reasoning?

**Comment by C-O-D** [comment]
You said you didn't understand what I meant and I tried to explain it to you again.
My main question, however, was why VB cannot be called up in Firefox mobile - I had the faint hope that you might be able to try it out and tell me what the problem is or maybe even change something so that it works 😁

**Comment by k-ivan** [comment]
Thank you, now I understand )

If there were a full-fledged API, it would be possible to improve support, but unfortunately, it is very limited.
Sorry that I couldn't help.

**Comment by C-O-D** [comment]
oh, that's really too bad but thanks anyway...

**Comment by k-ivan** [comment]
You're welcome.
