### ISSUE TITLE
Arrange bookmarks using drag & drop without filling the row

### ISSUE THREAD

**Issue by GitHub-Mike** [k-ivan/visual-bookmarks-chrome#195]
Would it be possible to add a setting so that the rows are not automatically filled when arranging the bookmarks? It will be sufficient if the empty "cells" are only at the end.

```
x x x
x x x x x x
x
x x x x
```

**Comment by k-ivan** [comment]
Hi!

Honestly, I didn’t quite understand what the expected result should be. Maybe this can be solved with custom styles. However, I’m not entirely sure what the outcome is supposed to look like.
Perhaps you could illustrate this in a screenshot?

**Comment by k-ivan** [comment]
Yes, in that case, you should try using custom CSS.

**Comment by GitHub-Mike** [comment]
I have just looked at it again. It can't be solved with CSS alone, because you need a feature to force a wrap. So the last bookmark in the "row" needs a special class or data attribute. Then a solution might be conceivable. A grid as a table would probably be better.

**Comment by k-ivan** [comment]
Unfortunately, I cannot offer a good solution at the moment, as the functionality is designed to rely on the browser's built-in bookmarks. This API does not provide additional fields where we could store auxiliary information that the extension could use. I believe cluttering fields like `title` is bad practice.  

The only possible approach is through CSS, but you're right—it requires hardcoding and fixed values.  

Sorry, but I am unable to help resolve this issue at the moment.

**Comment by GitHub-Mike** [comment]
> I believe cluttering fields like title is bad practice.

If there is no other way, you have to resort to such means. :-)

> Sorry, but I am unable to help resolve this issue at the moment.

Maybe if you could add the title as a class. Then you could create a rule using the CSS attribute selector. I can't think of anything else.

**Comment by k-ivan** [comment]
> If there is no other way, you have to resort to such means. :-)

I am not willing to agree to adding service information into fields not intended for this purpose. The native browser interface and other extensions will not parse these fields, truncating the service data added by my extension, which is very detrimental to the user experience.

> Maybe if you could add the title as a class. Then you could create a rule using the CSS attribute selector. I can't think of anything else.

Honestly, I don't see how this could help. Bookmarks already have a unique ID in their markup, but in this example, it won't provide any advantage.

It seems to me that for such an implementation, almost the entire interface would need to be redesigned, as it is completely incompatible with the current one. Essentially, this would mean entirely different logic and behavior.

**Comment by GitHub-Mike** [comment]
> I am not willing to agree to adding service information into fields not intended for this purpose. The native browser interface and other extensions will not parse these fields, truncating the service data added by my extension, which is very detrimental to the user experience.

I don't know exactly what you mean by that? I can already choose the title of the bookmark myself, can't I? And if I change "My bookmark" --> "My bookmark*", I don't see a problem.

> Honestly, I don't see how this could help. Bookmarks already have a unique ID in their markup, but in this example, it won't provide any advantage.

Thanks for the tip, I had completely overlooked that. Now there might be a possibility after all.

**Comment by k-ivan** [comment]
> I don't know exactly what you mean by that? I can already choose the title of the bookmark myself, can't I? And if I change "My bookmark" --> "My bookmark*", I don't see a problem.

If we put our service data into the `title` field, in our extension we can handle it in such a way that we don't parse it but instead display a proper title. However, other tools won't be aware of this and will display the contents of the `title` field as is. As a result, the service data, which is only necessary for my extension, will be shown as the title in the native interface. For instance, if the user removes my extension and switches to the native interface, the `title` field will contain a lot of clutter (left behind by my extension).

> Thanks for the tip, I had completely overlooked that. Now there might be a possibility after all.

In theory, you could use something like this — for example, every 10th bookmark starts a new section (just hypothetically). However, this approach would still require manual oversight.
```css
.bookmark:nth-child(10n) {
    grid-column: 1;
}
```

**Comment by GitHub-Mike** [comment]
I have now found a solution with float, in which the marked elements slide to the first position of the "row". Of course, this can still be improved.

```css
.grid {
    display: block;c
}
.bookmark {
    width: calc( ( 100% - ( var(--grid-columns) ) * var(--grid-gap) ) / var(--grid-columns) );
    float: left;
    margin: 0 var(--grid-gap) var(--grid-gap) 0;
}
.bookmark[title$="*"] {
    clear: both;
}
```

**Comment by k-ivan** [comment]
Good news. In that case, I think we can close the issue.

**Comment by GitHub-Mike** [comment]
Yes, we can do that. Thank you for your answers.

**Comment by k-ivan** [comment]
You're welcome.
