### ISSUE TITLE
[ Feature request ] Import and export settings

### ISSUE THREAD

**Issue by shellaaaron** [k-ivan/visual-bookmarks-chrome#20]
**Feature request Import and export settings**, I understand that there is a sync option also, Syncing is enabled and linked to my account.
but I have uninstalled and reinstall the extensions and all settings were lost

So, I think manually backup settings import and export would be much appreciated and import and export extension option would be a great feature in case change between computers and if remove the google chrome and reinstall sometimes for technical issues.

**Comment by k-ivan** [comment]
Hey @shellaaaron ! Maybe the option will be useful, I'll think about its implementation. Thanks!

**Comment by k-ivan** [comment]
Hey @shellaaaron! Added backup settings option in version 3.7.0. It can be found on the advanced tab on the options page.
Thank you for your participation.
