### ISSUE TITLE
Feature Request: Dowload all missing images (screenshots)

### ISSUE THREAD

**Issue by oliver-77** [k-ivan/visual-bookmarks-chrome#3]
If there is no way to import/export or save the images on a cloud drive, I think there should be a button like: "Download all missing images".

**Comment by k-ivan** [comment]
What do you mean. If you want to download all the pictures that were generated with the extension, then filesystem:chrome-extension://jdbgjlehkajddoapdgpdjmlpdalfnenf/persistent/images/ on this path you can extract them.

**Comment by oliver-77** [comment]
I mean if I am using a new Browser with this extension, there should be an option to redownload all screenshots of the bookmarks at once. So I don't need to cklick every bookmark for redownloading the screenshot.

**Comment by k-ivan** [comment]
The screenshot names now consist of the name + id.
Even if you unload all the files. On the new device when synchronizing bookmarks, the bookmark ids will be different, the pictures do not get attached
