### ISSUE TITLE
[ Feature request ] Allow extension URL instead of using it as home page in Chrome

### ISSUE THREAD

**Issue by shellaaaron** [k-ivan/visual-bookmarks-chrome#30]
Allowing the extension to be opened separately without having to make it as a chrome home page.

**Comment by k-ivan** [comment]
Hey @shellaaaron !
I would like to know a common opinion on this issue. A couple of people wrote about this possibility, but is it necessary for everyone? This can be done, but it is impossible as an option, that is, it will be either only by clicking on the icon or as the default tab.

**Comment by k-ivan** [comment]
At the moment I refuse to implement this feature.
