### ISSUE TITLE
[ Feature request ] Add option to add Most Visited Sites to be open in the page.

### ISSUE THREAD

**Issue by shellaaaron** [k-ivan/visual-bookmarks-chrome#31]
It will be great to add an option to add **Most Visited Sites** to be open in the page.

**Comment by k-ivan** [comment]
Good idea, I'll think about it.

**Comment by k-ivan** [comment]
As visual cards most likely not. Many difficulties with linking and unlinking screenshots. Since most of the functionality is made specifically for bookmarks.

Perhaps later, I will return to this issue, but for now I will close this issue.
