### ISSUE TITLE
[ Feature request ] Load all bookmark thumbnail at once !

### ISSUE THREAD

**Issue by shojimeguro** [k-ivan/visual-bookmarks-chrome#34]
Currently if you want to load thumbnail on bookmark, then you need to right click and press refresh thumbnail button one by one.

But this will become problem if you have hundreds or thousand bookmarks to refresh thumbnails with, tried export then import the bookmark again but it only loads icon.

So by implementing "refresh all thumbnails" button will save time and effort for lot of bookmarks. if you need some concept then you can see how vivaldi browser bookmark thumbnail does.

**Comment by k-ivan** [comment]
Hey @shojimeguro 
The option to update all bookmarks inside the active folder is already exists. You need to activate in the settings. After that, a thumbnail button will appear in the lower left corner.
![Untitled](https://user-images.githubusercontent.com/6150895/72407364-634bd380-3770-11ea-981a-1dddb933bea9.png)
![Untitled1](https://user-images.githubusercontent.com/6150895/72407365-634bd380-3770-11ea-97b7-271ae7cf2d68.png)

**Comment by shojimeguro** [comment]
oh the lower left button, just noticed since it perfectly blend in dark mode, ok last request : add them on context menu so when i right click the folder, it showed up refresh thumbnails.
![image](https://user-images.githubusercontent.com/10215304/72456028-75705500-37f6-11ea-8a87-c51f1d91938e.png)

**Comment by k-ivan** [comment]
For some reason I did not think about it, in theory it might work.  I’ll think about it soon. Thanks for the idea.

**Comment by shojimeguro** [comment]
> For some reason I did not think about it, in theory it might work. I’ll think about it soon. Thanks for the idea.

ok thank you

**Comment by shojimeguro** [comment]
![image](https://user-images.githubusercontent.com/10215304/72659881-e3846a00-39f8-11ea-822f-2925dc2fa51d.png)

also is it possible to update all including subfolder? i think i have around 20 subfolder so far so it willl not efficient to update 20 times.

Also the loaded thumbnail get reloaded again when i press it while i only re-load it to load several thumbnails.

**Comment by k-ivan** [comment]
> also is it possible to update all including subfolder? i think i have around 20 subfolder so far so it willl not efficient to update 20 times.

I can think about it, but in the distant future. Maybe a little while later a decision of the moment will come to me.

> Also the loaded thumbnail get reloaded again when i press it while i only re-load it to load several thumbnails.

This is the correct behavior because no one except you knows what needs to be updated and what is not

**Comment by shojimeguro** [comment]
> > also is it possible to update all including subfolder? i think i have around 20 subfolder so far so it willl not efficient to update 20 times.
> 
> I can think about it, but in the distant future. Maybe a little while later a decision of the moment will come to me.
> 
> > Also the loaded thumbnail get reloaded again when i press it while i only re-load it to load several thumbnails.
> 
> This is the correct behavior, because only you know what can be updated and what not

i see so it cannot detect succesful or failed load so it reload all of it. well this is just minor issue so it is optional.

but for subfolder is certainly required. so simply one click and all thumbnail loaded !

**Comment by k-ivan** [comment]
Hi @shojimeguro )
What do you think about the additional option in the settings, which will determine whether to generate thumbnails for subfolders?
If the option is enabled, then thumbnails are created including from subfolders, otherwise without subfolders
![image](https://user-images.githubusercontent.com/6150895/79335694-1c19de00-7f2b-11ea-9841-ed4f0f0b4040.png)

**Comment by shojimeguro** [comment]
sure this is great, thanks.

anyway is it possible to generate certain website thumbnail based on
images? i learned this from raindrop and when i put image hosting like
giphy, manga, or others, it shows the main image of the sites instead of
entire sites interface

**Comment by k-ivan** [comment]
Ok during this week add this setting.

But on the question about services I could not understand what you mean. Maybe you can clarify the screenshot or video?

**Comment by shojimeguro** [comment]
here is the screenshot of my raindrop for some website, as you can see it
able to generate thumbnail on main image pr video thumbnail of the website,
instead of entire webpage. makes it looks much better and more efficient.

[image: image.png]

[image: image.png]

**Comment by k-ivan** [comment]
Looks like the images are not uploaded

**Comment by shojimeguro** [comment]
oh sorry, this is because i use gmail to reply so i will reply on github to show the images.

![image](https://user-images.githubusercontent.com/10215304/79365516-ee598700-7f74-11ea-8364-21690e0cef68.png)

![image](https://user-images.githubusercontent.com/10215304/79365535-f285a480-7f74-11ea-9539-8d6da9433aed.png)

**Comment by k-ivan** [comment]
it’s like a thumbnail technique for a YouTube video?

**Comment by shojimeguro** [comment]
yes kind of, you can realize that youtube and manga website has their thumbnail on every page and raindrop simply generate this image as thumbnails instead of entire webpage

**Comment by k-ivan** [comment]
I will study this question. But so far it seems to me that raindrop does this on its servers using a special api.  By means of the browser I can only make window capture

**Comment by shojimeguro** [comment]
i see, well consider this as optional but will be great if it is possible.

at least now i can load all my bookmark and its subfolder at once.

**Comment by k-ivan** [comment]
The option will appear in version 3.10.0, the update may take 3-5 days.

**Comment by shojimeguro** [comment]
sure take your time, i will try to repopulate bookmark from raindrop so it
will imported to chrome
