### ISSUE TITLE
add back button

### ISSUE THREAD

**Issue by shojimeguro** [k-ivan/visual-bookmarks-chrome#35]
it is actually simple request but i think back button on left side of my visual bookmark will be more efficient instead of hover and clicking back button on browser.

**Comment by k-ivan** [comment]
Thanks for participating!

By the way, there was such functionality before. Now I’m thinking more about how to make useful menu from folders in the select list. But for now, I’m stuck on how best to visually fix it. As soon as I find a solution for visualizing the menu from folders, I can think about the back button.

**Comment by shojimeguro** [comment]
sure i will be waiting for it

**Comment by k-ivan** [comment]
Hey shojimeguro!
Added back button in the version 3.12.0
