### ISSUE TITLE
css query

### ISSUE THREAD

**Issue by yairbaricot** [k-ivan/visual-bookmarks-chrome#43]
Excuse my ignorance, I am trying to modify the custom css
Exactly the grid, because I want to change its aspect ratio
```
:root {
  --grid-column-width: 150 px;
  --grid-row-height: 258 px;
}
``` 

But it only changes when the width of the page is less than x resolution

Where can I modify the responsive size?

**Comment by k-ivan** [comment]
Hello @yairbaricot.
Size calculation takes place automatically, depending on the available width. But you can try a more specific entry.
```  
--grid-column-width: 150px !important;
--grid-row-height: 258px !important;
```

**Comment by yairbaricot** [comment]
Thank you, it was very helpful, I have already more or less achieved the desired result.

Can you add a description field?

![6ec8d](https://user-images.githubusercontent.com/66935265/85921460-7d72fd00-b84a-11ea-9c37-547a55acee9f.gif)

**Comment by k-ivan** [comment]
You're welcome!
I request bookmark information from the browser API. Unfortunately there is no description field (only a title).

**Comment by yairbaricot** [comment]
Okay, the app is very good.
A few last questions ...
Where are the local images stored?
I Can make a complete backup of all the configuration and its images?

**Comment by k-ivan** [comment]
1) Local images are saved in the working folder of the browser. See the whole list on this route `filesystem:chrome-extension://jdbgjlehkajddoapdgpdjmlpdalfnenf/persistent/images/`
2) All extension settings can be saved using browser synchronization or you can download the settings file locally using the export button on the options page. But with backup for thumbnails so far, everything is complicated. You will have to look for them in the working folder of the browser in User Data folder. In short, it seems to me it will be problematic.

**Comment by yairbaricot** [comment]
![Screenshot_33](https://user-images.githubusercontent.com/66935265/85931226-c352b400-b890-11ea-9ac8-81d8ad1a3947.jpg)

Sorry i couldn't locate the folder.

**Comment by k-ivan** [comment]
The folder where user files are stored is here `C:\Users\{your_username}\AppData\Local\Google\Chrome\User Data`
But, the API of the file system will not save raw files to disk, as it was not safe. Therefore, all files will be transformed (including their names). I doubt that it will turn out to find them.

**Comment by k-ivan** [comment]
You made me think that I might try to implement the ability to export images to zip archive and import them back into the extension.

Something to think about 🤔

**Comment by yairbaricot** [comment]
Which makes me wonder why doesn't it work directly with the file's source directory? It makes me think that when changing the thumbnail or deleting a bookmark with thumbnail it remains residual, taking up unnecessary storage space

**Comment by yairbaricot** [comment]
You could also specify a custom path to be able to customize these thumbnails.

**Comment by k-ivan** [comment]
> Which makes me wonder why doesn't it work directly with the file's source directory? It makes me think that when changing the thumbnail or deleting a bookmark with thumbnail it remains residual, taking up unnecessary storage space

no it’s not, when deleting a bookmark, I delete and thumbnail through fileSystem API(the file is really deleted)


> You could also specify a custom path to be able to customize these thumbnails.
> 
> If this existed, I think you wouldn't even have to create a backup option for the images. (Taking into account that the extension can recognize each file of the specified path and synchronize them with the bookmarks)

at the moment I can save files only through fileSystem API and his sandbox

**Comment by k-ivan** [comment]
I think the issue can be closed, if there is another question, reopen it.
