### ISSUE TITLE
more useful options

### ISSUE THREAD

**Issue by yoksi** [k-ivan/visual-bookmarks-chrome#47]
hi, first of all I am sure, that Your "speeddial from bookmarks" is best from all in Chrome Store right now
and as always there is space for make things even better ... 

for me it is adding more options in settings, example:
- option to hide (not so pretty) website titles - for thumbnails only clean look ... 
- or add switch for hide scrollbars
- and maybe extend "panel width" possibilities (95, 98% ?)

for that I currently using not so perfect or flexible custom CSS
```
.bookmark__caption {
display: none;}
.bookmark__wrap {
height: 115%;
background: transparent;}
```
thanks for good work

**Comment by k-ivan** [comment]
Hi @yoksi, and thank you, glad you like it )

I agree with you, I will make the title an option and the list of panel width options also needs to be expanded in the settings(I will do it as soon as possible).

Please clarify about the scrollbar, do you want to hide the vertical scrollbar on the page? If I understood correctly, then it seems to me better to remove it using css, for example:
```css
::-webkit-scrollbar {
    display: none;
}
```

**Comment by k-ivan** [comment]
Options will appear from version 3.14.0
