### ISSUE TITLE
Feature Request: Support "chrome://" URLs.

### ISSUE THREAD

**Issue by trashner** [k-ivan/visual-bookmarks-chrome#5]
I'd like to quickly access Chrome's "internal" pages, like `chrome://downloads/`, `chrome://extensions/`, `chrome-extension://<extension_ID>`, etc. Unfortunately those `chrome*://` URLs don't seem to be supported.

Could you please add support for them? (And maybe add their respective favicon as thumbnail?)

**Comment by k-ivan** [comment]
Hello @trashner.
For security reasons, chrome blocks the transition to local url ` chrome://`. In order for them to open, I will need to programmatically create a tab with this url. At the moment I would not like to process a click on the bookmark programmatically and check on `chrome://`. Maybe in the future.(when there will be a need to catch a click on the bookmark)

Also you can try to enable **Allow access to file urls** in the `chrome://extensions/`.

**Comment by trashner** [comment]
Too bad, but I understand. Allowing access to file URLs does not help, btw.

I wanted to make the switch from [Fast Dial](https://chrome.google.com/webstore/detail/fast-dial/fdnbdgmkhikelgaohpgdpcecklddmpaj), which works fine with `chrome*://` URLs, but unfortunately has other problems and seems to be abandoned. It is released under GNU GPLv3, in case you need inspiration. ;)

**Comment by k-ivan** [comment]
Thanks, I'll keep it in mind.
