### ISSUE TITLE
Please add steps how to build and load unpack extension in chrome.

### ISSUE THREAD

**Issue by lifehacker1** [k-ivan/visual-bookmarks-chrome#52]
Please add steps how to build and load unpack extension in chrome. 

I tried npm install in the main folder and then unpack. 
got  this error .'cannot load manifest.json'  then i changed the folder to static to point to manifest.json, this time the error is "cannot load option.html"

**Comment by k-ivan** [comment]
@lifehacker1 Hi. 
May I ask for what purpose?

**Comment by lifehacker1** [comment]
Hi K-ivan,

I am new to chrome extensions.I wanted to develop a simlar kind of extension as this one to manage my bookamarks.
I have around 500 bookamrks some organised and many in some random folder names.

I wanted to manage and use my bookmarks in a new tab efficiently.Though this app provides an easy way to view bokmarks but it is hard to mange them.So I wish to develope a feature to easy drag and drop  to merge folders,move bookmarks  for copy, cut,move like functionality.So that I also can even test my newly acquired frontend skills.

**Comment by k-ivan** [comment]
I created the environment exclusively for myself. If you want to create an extension, then my build environment is not required at all.

To run my environment, you need to do in the project folder:
```
npm i
npm start // watcher
npm run build // build
```
in order to load the extension into the browser, please see the developer documentation https://developer.chrome.com/extensions/getstarted

**Comment by lifehacker1** [comment]
Thanku K-ivan,
This should work.I did only npm start .it created a extension folder ,with alll required files complied i guess.I have unpacked this into chrome and it worked.

**Comment by k-ivan** [comment]
Difficult question. I've already thought about drag and drop. 
I think dnd sorting is a useful option and this behavior is also necessary.

**Comment by lifehacker1** [comment]
But drag drop for sorting is usefull only in the first or home folder,  In nested folders it has no use in my opinon.I have a lot of nested folders.which I some times create the to store all open tabs in a session ,as work arround to quickly save my work and exit.

**Comment by lifehacker1** [comment]
can we implement a mange bookmarks option ,or a switch kind of thing in which to achieve this using drag and drop

**Comment by k-ivan** [comment]
Sorry, I did not quite understand what setting with the switch is in question. More precisely, what does the setting do?

**Comment by k-ivan** [comment]
I will close this issue, due to lack of activity.
