### ISSUE TITLE
Drag and Drop Bookmarks to Folders

### ISSUE THREAD

**Issue by abg88** [k-ivan/visual-bookmarks-chrome#56]
I come from Opera and I'm finding this extension amazing. 
Apparently it's a Simple Speed Dial fork, which I was using and it's really good, but there are some features missing there.

Sadly there's still a feature missing in Visual Bookmarks, which is Drag and Drop Bookmarks to Folders.
Any chance of an update bringing this feature?

**Comment by k-ivan** [comment]
This is not very easy to implement.
But I am working on this possibility. I plan to move the folders that are in the drop-down select to the left sidebar, in this case I will be able to drag bookmarks to this sidebar. But I can't give exact dates, it all depends on the availability of free time.

**Comment by abg88** [comment]
I'm no Chrome programmer, but wouldn't a drag and drop be something like Cut a bookmark from a folder then Paste it into another under the hood? But I have no idea if it's really like that...

I really like how Visual Bookmarks is right now, and sidebar is something I've never been fond of. 
Drag and Drop is the only feature to make it perfect.

**Comment by k-ivan** [comment]
It's a little more complicated than you described. That's why I still haven't added it yet, there are a lot of nuances. 
The solution that I described is not final, I'm still thinking about this point, but at the moment the most obvious one for me.

**Comment by k-ivan** [comment]
Hi @abg88!

Since version 3.16.0 I added experimentally support for drag and drop to folders. So far I have abandoned the original plan that I described above. But I must warn you that at the moment it is not very trivial to implement, perhaps this implementation will not stick.

**Comment by k-ivan** [comment]
I hope that even in the current implementation it will be useful.

**Comment by abg88** [comment]
It's working really great. Congrats and thanks!

Another implementation that would be great is drag and drop to an above folder - so I can fix the mistake of dragging to a wrong folder. But it's not entirely necessary; as it is now, VB is working great! Thank you again!

**Comment by k-ivan** [comment]
Thank you for your participation 👍
