### ISSUE TITLE
Thumbnails disappear on reboot

### ISSUE THREAD

**Issue by berlihingen** [k-ivan/visual-bookmarks-chrome#58]
On reboot, it loses all the thumbnails – uploaded from disk or internet. Any idea how to fix it on ms Edge? Thanks

**Comment by k-ivan** [comment]
Perhaps you have configured something like clearing the browser cache folder or something similar.
Thumbnails are stored in the working folder of the browser, if they disappear, then something clears this folder.

**Comment by berlihingen** [comment]
That's true, cache cleaning on shutdown is set, will try to switch it off.

Also, can you please provide an alternative URL for "Thumbnail service", as the current one sends some misleading results?

**Comment by k-ivan** [comment]
is it because it shows the meta logo instead of the thumbnails?

You can specify any to your taste.
I have not been interested in this topic for a long time, so I don’t know which of them are currently presented.

**Comment by berlihingen** [comment]
No, it just shows the wrong logo for some sites, but this wouldn't be a problem if I found a way to protect my uploaded logos from purging with the cache.  
And, while you kindly answer my questions :) can you please give a Custom CSS snippet to make the dial's background more transparent?

**Comment by k-ivan** [comment]
> And, while you kindly answer my questions :) can you please give a Custom CSS snippet to make the dial's background more transparent?

Sure
```css
:root {
  --bookmark-bg: rgba(0 0 0 / .05) // (0 0 0 black color / 0.05 transparent) transparent from 0 to 1
}
```

**Comment by berlihingen** [comment]
I left Edge's cache to OS management and everything now is in its right places, including my logos and transparent background. Thank you very much!

**Comment by k-ivan** [comment]
It's my pleasure )

**Comment by k-ivan** [comment]
@berlihingen I forgot to add that I have already sent the version for the MS Edge store for review. If it passes the review, then the extension can be installed from MS Edge store.

**Comment by berlihingen** [comment]
Great! Now when I've got how to play with custom CSS, I like this addon even more:)

**Comment by k-ivan** [comment]
@berlihingen now if you want you can install the version from the microsoft store 
https://microsoftedge.microsoft.com/addons/detail/idfbjjfgccflicphjlpbomcklaehplha

**Comment by berlihingen** [comment]
Will do that, thanks! BTW, can't find the right line to change the menu button color – that black circle with three vertical dots?

**Comment by k-ivan** [comment]
```css
.bookmark__action {
    background-color: #bc3535;
}
```

**Comment by berlihingen** [comment]
Thanks, reinstalled it just now with no issues.
