### ISSUE TITLE
suggestion: quick go back

### ISSUE THREAD

**Issue by yoksi** [k-ivan/visual-bookmarks-chrome#59]
hello, I have one little suggestion targeted for lazy people :)

If you have more complex SpeedDial/favorites tree with some layers of subfolders then you want possibility how to quickly go onelevel back/up ...like in file manager... 

fastest is something like 2x mouse click to empty space to go level up
or more accurate way add small shortcut icon to down right 
or simple replace last visible dial with this feature (but you lost one dial)

**Comment by yoksi** [comment]
directly under native browser arrow "go back", which I using right now if I want go back from folder? that is not much helpful (for me at least) :)

but maybe add option for change position (up/down left/right corner)

**Comment by yoksi** [comment]
if position will not be fixed for this button (thanks to custom CSS) then everything is OK :)

**Comment by k-ivan** [comment]
Added this feature in version 5.1.0. But I refused the solution as in the screenshot above. And I placed the column inside the bookmarks, which is more like a file system.

But you can still use your styles to position it however you like.
![image](https://user-images.githubusercontent.com/6150895/211164588-5714a5f3-7b78-4abb-bb3b-0b5ffadd21c1.png)

I think this issue can be closed.
