### ISSUE TITLE
предложение: цвет папок, перенос закладки в папку

### ISSUE THREAD

**Issue by inudder** [k-ivan/visual-bookmarks-chrome#62]
Добавьте, пожалуйста, возможность **изменять цвет папок**, чтобы легче ориентироваться, но я нашел вариант дописать Emoji в название папки.

Не хватает функции **перенос закладки в нужную папку** через правый клик.

**Comment by k-ivan** [comment]
Привет @inudder !

1) Вы имейте ввиду фон папки или иконки. Из-за того что сейчас папка может отображать иконку или превью сайтов, не понятно о чем речь. Если раскрашивать сам фон, то нужно над этим подумать, насколько это полезно. Так как благодаря кастомному css вы можете легко кастомизировать  почти все)
пример для папок
 ```css
.bookmark--folder[data-id="413"] .bookmark__wrap {
  background: tomato;
}
 .bookmark--folder[data-id="453"] .bookmark__wrap {
   background: royalblue;
}
 ```
 получится
 ![image](https://user-images.githubusercontent.com/6150895/111021544-3334aa80-83de-11eb-80da-c21d311308ee.png)
 Я согласен, что это не очень тривиально для пользователей незнакомых с CSS.  Но в тоже время здесь возможно поменять практически все.

2) Не планируется. На данный момент есть уже 2 возможности переносить папки: 
* при перетаскивание закладок, можно помещать ее внутрь папки(относится ко всем папкам на этом уровне). То есть в момент перетаскивания на всех папках в текущей появляется дропзона в которую нужно переместить закладку.
* при выборе в контекстном меню пункта редактировать(внутри открывшегося модального окна)
Создавать такую возможность в контекстном меню считаю избыточным, так как уже есть 2 способа, к тому же есть еще один жирный минус помещать это в контекстное меню. У пользователя может быть очень много папок с большой вложенной структурой, которая может даже в экран не убираться. В таком случае даже страшно представить как это все будет выглядеть.

**Comment by inudder** [comment]
Спасибо за развернутый ответ. Благодаря вашему объяснение, потребность в цвета иконок папки отпадает, потому что я поставил в настройках  "Миниатюры сайтов на папке вместо иконки" и применил CSS по вашему примеру. Не сразу догадался как ID папки получать, но нашел, нужно было просто подвести к папке и посмотреть урл в левом нижнем крае.
Как узнать что еще можно менять? Смотрел консоль со вкладкой "Visual Bookmarks" не нашел упоминания .bookmark--folder, с помощью чего можно увидеть CSS Для элементов?
![gChUttGfkk](https://user-images.githubusercontent.com/23030021/111026901-8713b380-841f-11eb-9e28-bfaca8603f03.png)

Мне подошел вариант переноса вкладки через модальное окно пункта редактировать. А через дропзону есть проблема, например папки сверху, а вкладку перенести нужно снизу, до которой я добрался через скролл, соответственно верхние папки не видно.

**Comment by k-ivan** [comment]
Касаемо момента кастомизации. Вы можете перейти на вкладку - Элементы. Там будет все дерево документа. Затем можно нажать кнопочку слева, после этого, можно кликнуть по тому элементу на странице, который Вы хотите по редактировать. Справа в консоли будут стили относящиеся к этому елементу
1) ![Безымянный](https://user-images.githubusercontent.com/6150895/111029442-a86ba400-840d-11eb-8213-158225e47232.png)
2) ![image](https://user-images.githubusercontent.com/6150895/111029432-9be74b80-840d-11eb-92df-15756bc0ce21.png)
id папок как раз кстати будет видно когда перейдете на папку элементы

Касаемо перемещения папок с помощью перетаскивания, даже если закладка где-то внизу, а папки вверху, Вы можете начать тащить закладку к верхней границы окна просмотра, страница начнет скролиться вверх(аналогично и для низа), главное не отпускайте закладку, пока не дойдете до нужного места. Перетаскивание поддерживает скрол.
