### ISSUE TITLE
Translation into Hungarian

### ISSUE THREAD

**Issue by FowlerJohn** [k-ivan/visual-bookmarks-chrome#70]
{
   "add_bookmark": {
      "message": "Hozzáadás a könyvjelzőkhöz"
   },
   "advanced_setting": {
      "message": "Speciális"
   },
   "advanced_settings": {
      "message": "Speciális beállítások"
   },
   "alert_create_fail_bookmark": {
      "message": "- Új mappa hozzáadása csak egy címet igényel \n- Új könyvjelző hozzáadásához egy címre és egy URL-címre van szükség."
   },
   "alert_file_type_fail": {
      "message": "Rossz fájltípus\n Érvényes fájltípusok (jpg | jpeg | png | webp)"
   },
   "alert_update_fail_bookmark": {
      "message": "Egy meglévő könyvjelző szerkesztéséhez a Chrome-ban egy címre és egy érvényes URL-re is szükség van\n\n Például az érvényes URL-címek a következővel kezdődnek: \n - http:// \n - https:// \n - ftp://"
   },
   "auto_generate_thumbnail": {
      "message": "Miniatűrkép generálása könyvjelző létrehozásakor"
   },
   "background": {
      "message": "Háttér"
   },
   "backup_settings": {
      "message": "Importálás / exportálás beállítások"
   },
   "backup_settings_description": {
      "message": "Biztonsági mentés csak a kiterjesztés beállításairól, kivéve a könyvjelzőket és a képeket"
   },
   "btn_apply": {
      "message": "Alkalmaz"
   },
   "btn_back": {
      "message": "Kész"
   },
   "btn_close": {
      "message": "Mégse"
   },
   "btn_save": {
      "message": "Mentés"
   },
   "careful_change": {
      "message": "Legyen óvatos, ha meg akarja változtatni ezt az opciót"
   },
   "choose_file": {
      "message": "Válasszon ki egy fájlt"
   },
   "clear_local_images": {
      "message": "A helyi képeket tartalmazó mappa törlése"
   },
   "color": {
      "message": "Szín"
   },
   "color_theme": {
      "message": "Színséma"
   },
   "confirm_clear_sync_settings": {
      "message": "Biztos, hogy törölni szeretné az összes korábban szinkronizált adatot az újrakezdéshez? ?"
   },
   "confirm_delete_bookmark": {
      "message": "Biztos, hogy törölni szeretné a könyvjelzőt? ?"
   },
   "confirm_delete_folder": {
      "message": "Biztos, hogy törölni szeretné a mappát és annak minden tartalmát? ?"
   },
   "confirm_delete_image": {
      "message": "Kép törlése?"
   },
   "confirm_delete_images": {
      "message": "Biztos vagy benne? Minden helyi kép törlésre kerül!"
   },
   "confirm_restore_default_settings": {
      "message": "Biztos, hogy vissza akarja állítani az alapértelmezett beállításokat?"
   },
   "confirm_sync_remote_settings": {
      "message": "Korábban szinkronizáltad az adatokat!!!\n Szeretné felülírni a jelenlegi helyi beállításokat a korábban elmentett távoli beállításokkal?"
   },
   "contextmenu_capture": {
      "message": "Miniatűr frissítése"
   },
   "contextmenu_copy_link": {
      "message": "Link címének másolása"
   },
   "contextmenu_edit": {
      "message": "Szerkeszt"
   },
   "contextmenu_incognito": {
      "message": "Megnyitás inkognitó módban"
   },
   "contextmenu_open_all": {
      "message": "Az összes megnyitása"
   },
   "contextmenu_open_all_window": {
      "message": "Mindent új ablakban nyit meg"
   },
   "contextmenu_remove": {
      "message": "Eltávolítás"
   },
   "contextmenu_tab": {
      "message": "Megnyitás új lapon"
   },
   "contextmenu_upload": {
      "message": "Feltöltés a számítógépről"
   },
   "contextmenu_window": {
      "message": "Megnyitás új ablakban"
   },
   "dark_theme": {
      "message": "Sötét"
   },
   "default_folder_show": {
      "message": "Megjelenítendő alapértelmezett mappa"
   },
   "default_title": {
      "message": "Vizuális könyvjelzők"
   },
   "dial_width": {
      "message": "Panel szélessége"
   },
   "drag_and_drop": {
      "message": "Drag & Drop engedélyezése"
   },
   "edit_bookmark": {
      "message": "Könyvjelző szerkesztése"
   },
   "enable_synchronization": {
      "message": "Szinkronizálás engedélyezése"
   },
   "ext_desc": {
      "message": "Egyszerű gyorshívó könyvjelző oldal, beleértve a keresést, a könyvjelzők hozzáadását, szerkesztését, törlését és áthúzását."
   },
   "ext_name": {
      "message": "Vizuális könyvjelzők"
   },
   "folder_preview": {
      "message": "A webhelyek miniatűrjei egy mappában ikon helyett."
   },
   "folder_preview_description": {
      "message": "Amíg ez a beállítás be van kapcsolva, az ikon vagy az egyéni kép helyett 4 véletlenszerű oldal miniatűrképe jelenik meg a mappából."
   },
   "general_setting": {
      "message": "Általános"
   },
   "google_services": {
      "message": "Google szolgáltatások"
   },
   "import_settings_failed": {
      "message": "Nem sikerült elemezni a beállításfájlt!"
   },
   "import_settings_success": {
      "message": "Importált beállítások."
   },
   "label_folder": {
      "message": "Mappa"
   },
   "label_title": {
      "message": "Cím"
   },
   "label_url": {
      "message": "URL"
   },
   "light_theme": {
      "message": "Világos"
   },
   "local_image": {
      "message": "Kép a számítógépről"
   },
   "no_image": {
      "message": "Háttérkép nélkül"
   },
   "no_image_text": {
      "message": "Téma háttérkép nélkül"
   },
   "not_found_link_text": {
      "message": "Könyvjelzők sáv"
   },
   "not_found_text": {
      "message": "Nem találja a mappát az azonosító alapján. Lehet, hogy nem szinkronizálta a könyvjelzőket, vagy törölte vagy | áthelyezte ezt a mappát."
   },
   "notice_bg_image_updated": {
      "message": "A háttérkép megváltozott"
   },
   "notice_bookmark_created": {
      "message": "Létrehozott könyvjelző"
   },
   "notice_bookmark_exist": {
      "message": "A könyvjelző már létezik"
   },
   "notice_bookmark_removed": {
      "message": "Könyvjelző eltávolítva"
   },
   "notice_bookmark_updated": {
      "message": "Könyvjelző módosítva"
   },
   "notice_cant_find_id": {
      "message": "Nem találom a mappát az azonosító alapján. Talán nem szinkronizáltad a könyvjelzőket?"
   },
   "notice_folder_removed": {
      "message": "Mappa eltávolítva"
   },
   "notice_image_removed": {
      "message": "A kép eltávolításra került"
   },
   "notice_images_removed": {
      "message": "Minden kép törlésre került"
   },
   "notice_reset_default_settings": {
      "message": "Az alapértelmezett helyi beállítások visszaállítása"
   },
   "notice_save_settings_success": {
      "message": "A beállítások sikeresen mentve"
   },
   "notice_sync_settings_cleared": {
      "message": "Adatok szinkronizálása törölve"
   },
   "notice_thumb_image_updated": {
      "message": "Könyvjelző miniatűrök frissítése"
   },
   "notice_thumbnails_update_complete": {
      "message": "A miniatűrök frissítése befejeződött"
   },
   "number_of_columns": {
      "message": "Oszlopok száma"
   },
   "open_link_newtab": {
      "message": "Könyvjelző megnyitása új lapon"
   },
   "option_customstyle": {
      "message": "Egyéni CSS"
   },
   "option_not_sync": {
      "message": "Az opció nincs szinkronizálva"
   },
   "options": {
      "message": "Beállítások"
   },
   "os_theme": {
      "message": "OS téma"
   },
   "placeholder_input_customstyle": {
      "message": "Adja meg az egyéni CSS-t (haladó felhasználók számára)"
   },
   "placeholder_input_search": {
      "message": "Keresés a könyvjelzőkben"
   },
   "placeholder_input_title": {
      "message": "Adja meg a könyvjelző címét"
   },
   "reset_local_default": {
      "message": "Helyi beállítások visszaállítása alapértelmezett értékekre"
   },
   "reset_sync_text": {
      "message": "Szinkronizált adatok törlése a kiszolgálóról"
   },
   "save_to_current_folder": {
      "message": "Mentés az aktuális mappába"
   },
   "show_bookmark_title": {
      "message": "Könyvjelző címének megjelenítése"
   },
   "show_contextmenu_item": {
      "message": "Megjelenítés a helyi menüben"
   },
   "show_create_column": {
      "message": "Könyvjelző hozzáadására szolgáló oszlop megjelenítése"
   },
   "show_favicon": {
      "message": "A kedvencek ikon megjelenítése a cím mellett"
   },
   "show_header_bar": {
      "message": "Keresősáv és mappaválasztás megjelenítése"
   },
   "show_settings_icon": {
      "message": "A beállítások ikonjának megjelenítése"
   },
   "thumbnail_help": {
      "message": "[URL] kód helyébe a gyorstárcsázási URL lép."
   },
   "thumbnail_service": {
      "message": "Miniatűr szolgáltatás"
   },
   "thumbnails_creation": {
      "message": "Miniatűrök létrehozása: $start$ a $total$-ból",
      "placeholders": {
         "start": {
            "content": "$1"
         },
         "total": {
            "content": "$2"
         }
      }
   },
   "thumbnails_update_button": {
      "message": "Miniatűrök frissítése gomb"
   },
   "thumbnails_update_recursive": {
      "message": "Beleértve az almappákat is"
   },
   "thumbnails_update_recursive_note": {
      "message": "Ha az \"$option$\" opció engedélyezve van",
      "placeholders": {
         "option": {
            "content": "$1"
         }
      }
   },
   "thumbnails_update_warn": {
      "message": "A miniatűrök frissítése befolyásolhatja a teljesítményt (a mappában lévő könyvjelzők számától és a számítógép teljesítményétől függően)."
   },
   "url_field_tip": {
      "message": "Adja meg az URL-címet, vagy hagyja üresen, ha létre akarja hozni a mappát."
   },
   "url_image": {
      "message": "Kép az URL-címről"
   },
   "version": {
      "message": "Verzió"
   },
   "vertical_center": {
      "message": "Függőlegesen középre igazítás"
   },
   "view_setting": {
      "message": "Nézet"
   }
}

**Comment by k-ivan** [comment]
Hello @FowlerJohn!

Thanks for the contribution to the translations. Could you please keep the original key order as in other language files(it is now sorted alphabetically)? Or I will correct it myself, but much later.

For convenience, you could put the result in `code` inside comment
<pre>
```json
json data here
```
</pre>

**Comment by FowlerJohn** [comment]
Dear Ivan!

In principle I have not changed the order.
I translated the original English "messages.json" file into English in 
Notepad++. I pasted it into GitHub with "Ctrl+C and Ctrl+V".
I attach the compressed file.
Note that it works fine.

Hi,
John

John Fowler <https://fowler.hu>

------ Eredeti üzenet ------
Feladó: "Ivan" ***@***.***>
Címzett: "k-ivan/visual-bookmarks-chrome" 
***@***.***>
Másolat: "John Fowler" ***@***.***>; "Mention" 
***@***.***>
Elküldve: 2021. 07. 08. 17:24:32
Tárgy: Re: [k-ivan/visual-bookmarks-chrome] Translation into Hungarian 
(#70)

**Comment by k-ivan** [comment]
This is strange since the sorting does not match.
Then it looks like the notepad++ sorted.

**Comment by k-ivan** [comment]
Updated to version 3.17.0. Check, please)

**Comment by FowlerJohn** [comment]
Szia Iván!

Letöltöttem a GitHub-ra, "hu" mappába betett fájt.
Teszteltem a legújabb MS Edge-ben (Chromium).
Tökéletesen működik.

Üdv,
John

John Fowler <https://fowler.hu>

------ Eredeti üzenet ------
Feladó: "Ivan" ***@***.***>
Címzett: "k-ivan/visual-bookmarks-chrome" 
***@***.***>
Másolat: "John Fowler" ***@***.***>; "Mention" 
***@***.***>
Elküldve: 2021. 07. 08. 19:06:49
Tárgy: Re: [k-ivan/visual-bookmarks-chrome] Translation into Hungarian 
(#70)

**Comment by k-ivan** [comment]
Thanks for the help with the Hungarian translation. I close the issue, if after the update there are problems with the Hungarian language, just reopen this issue.

**Comment by FowlerJohn** [comment]
All right!
Thank you!

John Fowler <https://fowler.hu>

------ Eredeti üzenet ------
Feladó: "Ivan" ***@***.***>
Címzett: "k-ivan/visual-bookmarks-chrome" 
***@***.***>
Másolat: "John Fowler" ***@***.***>; "Mention" 
***@***.***>
Elküldve: 2021. 07. 08. 19:34:52
Tárgy: Re: [k-ivan/visual-bookmarks-chrome] Translation into Hungarian 
(#70)
