### ISSUE TITLE
Mobile Version

### ISSUE THREAD

**Issue by C-O-D** [k-ivan/visual-bookmarks-chrome#72]
Hi there,
thank you very much for this great extension, use it for quite some time now with Vivaldi on my desktop and I absolutely love it.
However, I recently discovered Kiwi browser for my mobile phone which fortunately supports extensions and I was happy to see that VB is working on my Android phone too (in comparison to many other start page extensions).
It looks very nice and does work so far but one problem is that the thumbnail generation doesn't work. It opens a new tab but the thumbnail still shows a generated logo instead of a screenshot of the website.
The other thing is that I just get two columns to show on the page but there would be sufficiant space for at least three if not four columns on my 2560x1440 display. If I switch to 'desktop version' I can see that it looks nice with three columns but then the thumbnail titles and the search bars are to small. I could live with that but unfortunately Chrome / Kiwi don't support permanent desktop mode on a site basis.
So my question is, would you consider to make a mobile-friendly version or to make it detect a phone and then change the layout accordingly?
I would be very grateful for this effort and above all since there's absolutely no alternative in the chrome store - at least for me...

Best regards

**Comment by k-ivan** [comment]
Hi @C-O-D 

I did a few fixes:
1) returned the settings icon on small screens
2) fixed the settings page on small screens
3) reduced the default size of cards for display (to 80px for width), but this is the limit for the normal view, I can’t reduce it further. I hope this given size is enough to display 3 cards in a row.

Version with changes 3.17.1 will be published soon, after checking in the extension store.

**Comment by C-O-D** [comment]
Hey Ivan,
thank you very very much - this is much better now!
I can get three thumbs in a row. The settings button is accessible although it's sitting behind the search bar or the back button but it's at least clickable (through) which is ok for me. Maybe you could shrink just the search bar on smaller screens so that the button remains visible but I wouldn't call that vital.
Also, if the title font would be a tad smaller it would look absolutely perfect (but also certainly not vital).
Do you think you finally can get the thumbnail creation to work?
However, I am very grateful so far, thanks again!

Best regards,
Eric


----------------------------------------

29.08.2021 12:14:05 Ivan ***@***.***>:

> Hi @C-O-D[https://github.com/C-O-D]
> 
> I did a few fixes:
> 
1. > returned the settings icon on small screens
2. > fixed the settings page on small screens
3. > reduced the default size of cards for display (to 80px for width), but this is the limit for the normal view, I can’t reduce it further. I hope this given size is enough to display 3 cards in a row.

**Comment by C-O-D** [comment]
This is how to look now:


 [cid:eu.faircode.email.7125]

----------------------------------------

29.08.2021 12:14:05 Ivan ***@***.***>:

> Hi @C-O-D[https://github.com/C-O-D]
> 
> I did a few fixes:
> 
1. > returned the settings icon on small screens
2. > fixed the settings page on small screens
3. > reduced the default size of cards for display (to 80px for width), but this is the limit for the normal view, I can’t reduce it further. I hope this given size is enough to display 3 cards in a row.

**Comment by k-ivan** [comment]
Regarding the width of the input or the size of the headers, you can set your own styles on the options page. I believe that this is much better than rigidly defining such behavior for everyone. If you are unfamiliar with css, I can describe to you an example of how to do this.

Unfortunately, there is no time to understand the thumbnails yet. But it is very likely that it is the browser itself or its security policy or the lack of the necessary API. That is, it is unlikely that it will be possible to correct this.

**Comment by C-O-D** [comment]
Hallo,
you're right, I can try it by myself.
I additionally wanted to remove the scrollbar and I also had to shift the back-button to the right.
So I added this via the config page:
_____________________________

::-webkit-scrollbar {
    display: none;
}
.form-control {
    margin: auto;
    width: 78%;
}
.field-icon {
    left: 37px;
}
.back {
    margin-left: 44px;
}
.bookmark {
    font-size: 13px;
}
_____________________________

...and got this:


 [cid:eu.faircode.email.7136]

...and I'm quite satisfied with it.
Only thing left is to make the config button disappear while scrolling down or to make it scrollable with the rest of the page, otherwise get this:


 [cid:eu.faircode.email.7137]

Last question would be if you could imagine to implement a configurable dropdown search bar for different search engines (like Firefox Mobile has in the address bar)? Surely you get seperate extensions for that purpose but it would be much more convenient to have it on the start page.

Ok, best regards again,
Eric

----------------------------------------

29.08.2021 17:52:45 Ivan ***@***.***>:

**Comment by k-ivan** [comment]
> Only thing left is to make the config button disappear while scrolling down or to make it scrollable with the rest of the page, otherwise get this:

Yes, there is a nuance here, since at the moment it is not the `body` of the document that is scrolled, but the `.app` element

So you can give the button absolute positioning
```css
.settings-link {
  position: absolute;
}
```
Since you have already hidden the scroll bar, now you can remove the scrolling of the `.app` block and return the scrolling for the body. 
![image](https://user-images.githubusercontent.com/6150895/131384590-5ba610bc-bc7c-4b68-9908-3222af25b022.png)
```css
.app {
    height: unset;
    overflow-y: unset;
    overflow-x: unset;
}
```
and
```css
body {
    overflow: auto !important;
}
```
After that, the button with settings will start scrolling.

**Comment by C-O-D** [comment]
Hey, thank you very much - that helped 👍

Have a good night,
Eric

----------------------------------------

30.08.2021 20:16:25 Ivan ***@***.***>:

**Comment by k-ivan** [comment]
I am glad to help ;)
