### ISSUE TITLE
Suggestion- see all your folders when trying to save a new webpage

### ISSUE THREAD

**Issue by visbook** [k-ivan/visual-bookmarks-chrome#73]
Hi k-ivan and thankyou for providing this brilliant extension.

I have about 35 subject folders inside V-B but have an issue when I want to save a new webpage into one of these folders.
I right click on the webpage > click "add to bookmarks" > click "Bookmarks" but on the vertical list it only displays a maximum of 24 folders, so to save the webpage into one of the not listed folders, I have to click "Save" and then open V-B and move it to the correct folder using the Edit function.

Is there a way to show all of the folders in the list?

TIA

**Comment by k-ivan** [comment]
Hi visbook!

It is very interesting. I will try to simulate this bug and fix it. A little later, I'll write here.

Thank you for helping to improve the project!

**Comment by k-ivan** [comment]
Strangely, there are no limits on items in the documentation.
@visbook  сould you try to reload the extension and check if the folders appear?
![Снимок экрана 2021-09-28 113637](https://user-images.githubusercontent.com/6150895/135053263-8b169130-e710-4250-8c83-7641117fd151.png)

**Comment by visbook** [comment]
Hi k-ivan
Thank you for the quick response,
I tried that but it made no difference, but I think I have solved the issue myself.

I clicked the "Details" tab as shown in your screengrab above, then chose "Extension options" from the menu.
I selected the "General" tab, then closed the slider to the "Show in context menu" option.

I closed and reopened the browser, then repeated the above steps and slid the slider of the "Show in context menu" to the right and now all the folders 35 folders were in the list.

**Comment by k-ivan** [comment]
Yes, I noticed this, the problem exists. Until I got to this, but a fix for this bug is in the plans.

**Comment by k-ivan** [comment]
Hi visbook!

Starting from version `3.18.0` the context menu should automatically update if the folder structure changes.

**Comment by visbook** [comment]
Thanks k-ivan, all good and your work is much appreciated.
