### ISSUE TITLE
Error in language files

### ISSUE THREAD

**Issue by miroslaw-zylewicz** [k-ivan/visual-bookmarks-chrome#76]
Code HTML:
`<div class="tbl__setting" data-locale-message="customstyle">Custom CSS</div>`

Language files:
`"option_customstyle": { "message": "Custom CSS" }`

---

Code HTML:
`<button class="settings-trigger" data-local-message="service_settings_btn">Tune</button>`

Language files:
`"service_settings_btn": { "message": "Tune" }`

---

Code HTML:
`<span class="c-upload__name" data-locale-message="import">Import</span>`
`<button class="btn md-ripple" data-locale-message="export" id="export">Export</button>`

Language files:
``

---

Code HTML:
`<button class="info-btn md-ripple" id="info"><svg width="24" height="24"><use xlink:href="/img/symbol.svg#info_outline"/></svg></button>`

Language files:
``

---

Code HTML:
`<button class="settings-close md-ripple ripple-container" data-ripple-center=""> <svg width="16" height="16" class="icon-times"> <use xlink:href="/img/symbol.svg#close"></use> </svg> </button>`

Language files:
` "btn_close": { "message": "Cancel" }`

---

Code HTML:
`<title>Options</title>`

Code HTML:
`"options": { "message": "Options" }`

**Comment by k-ivan** [comment]
Thank you Miroslaw. Very much appreciated for your help!
I will fix it in the next few days. By the way, the buttons have icons inside, so they are without text.
