### ISSUE TITLE
Some pages do not have enough time to fully load before a screenshot is taken

### ISSUE THREAD

**Issue by Feans** [k-ivan/visual-bookmarks-chrome#80]
Some pages do not have time to fully load before a screenshot is taken. For example, pages with videos or frames (vk.com, Archive.org , and many other video websites). I think adding the option "set the time in seconds for page loading" would solve the problem in most cases. For example, it would be possible to set a delay of 10 seconds after which a screenshot is taken. I have been using your extension for a long time, and this problem has existed from the very beginning on many video websites.

Examples:
vk https://c2n.me/4e4bZns.jpg
archive.org https://c2n.me/4e4c4rL.jpg
megogo.ru https://c2n.me/4e4c7Sy.jpg
ivi.ru https://c2n.me/4e4ca5G.jpg

**Comment by k-ivan** [comment]
Hello Feans!  Thanks for the feedback!  

I agree, this occurs on heavy pages, this is a good reason to think about how to fix or minimize this problem.
I'll try to do it as soon as I have time.

**Comment by k-ivan** [comment]
Hello @Feans!

I have added a delay option to the settings. The default value is 0.5s, the maximum is 15s, I think this is enough for most cases.
I think values over 15 will be redundant and uncomfortable.

**Comment by Feans** [comment]
Thanks, now it works.
