### ISSUE TITLE
Suggestion- auto close bookmarked pages

### ISSUE THREAD

**Issue by visbook** [k-ivan/visual-bookmarks-chrome#82]
Hi k-ivan

Would it be possible to add an option slider where you can choose the following-
once a webpage has been bookmarked the page will close itself and you don't have to manually click **X** on the tab bar to close the page.
This would be a very useful feature as I often have 20-30 tabs open and rapidly save pages of interest to look at later but then can't always remember if I've already saved the page when scrolling through the tabs again.
If the tab could close once bookmarked, I would know any tabs remaining have not yet been saved.

Thanks for creating an awesome extension and the very best wishes for the New Year

**Comment by k-ivan** [comment]
Hi visbook! Thanks for suggestion!
I added this option in v3.24.0.
But the tab will be closed when the bookmark is saved via the extension icon in the context menu. To avoid confusion when using native browser buttons.

**Comment by k-ivan** [comment]
I think this issue can be closed.

**Comment by visbook** [comment]
Thanks for the fast implementation k-ivan, works great and just what I was looking for.
