### ISSUE TITLE
Doesn't generate thumbnails

### ISSUE THREAD

**Issue by Maxxee** [k-ivan/visual-bookmarks-chrome#83]
The thumbnail generation feature is extremely broken.
Installed the extension, thumbnails didn't work.
After some tries it suddenly worked.
After generating 10 thumbnails it suddenly stopped working.
Refreshing thumbnail doesn't help.
Refreshing the tab doesn't help.

Setting the extension's site access from default On click, which was able to generate the first 10 thumbnails, to On all sites seems to help. Setting On specific sites also doesn't work.

Horrible experience.

**Comment by k-ivan** [comment]
If the experience is terrible, uninstall the extension, that should definitely help.

**Comment by Maxxee** [comment]
Whatever, go fuck yourself if you can't handle constructive feedback.

**Comment by k-ivan** [comment]
you are crazy

**Comment by Maxxee** [comment]
What does crazy mean? Do you think you are "normal"?

You are just a whiny distorted wannabe programming fuck with a big mouth. Do not forget, you started the beef, not me.
