### ISSUE TITLE
New version is not compatible with older chrome

### ISSUE THREAD

**Issue by Feans** [k-ivan/visual-bookmarks-chrome#89]
After the last update, the extension stopped working in my version of Chrome (white screen, instead of bookmarks). I'm using the old 80's version for certain reasons. However, **I could not find the old versions of the extension** for earlier versions of Chrome in the repository to reinstall it. Is it possible to find older versions?

Anyway, the old version should not be automatically updated and replaced with a new one, because it is incompatible with the old version of chrome. In this regard, you should **correctly specify the requirements for the chrome version in the google store**, and not indicate that it will work in the older chrome versions. Because it won't.

**Comment by k-ivan** [comment]
Old versions can be found here https://www.crx4chrome.com/s.php?s=visual%20bookmarks for example.

**Comment by Feans** [comment]
![image](https://c2n.me/4fGJBlw.jpg)

**Comment by k-ivan** [comment]
next step
click on the link `newtab.js`
![image](https://user-images.githubusercontent.com/6150895/168870457-e235311c-0496-4acd-beec-2600fc34ba0c.png)
you will see the source tab
there you will need to find 2 curly braces at the bottom of the window and click on them
![image](https://user-images.githubusercontent.com/6150895/168871528-ce1ba343-9252-4893-bec2-f6ce549448c2.png)
then go back to the console tab and click on the link `newtab.js` again
the source tab will open again, but already at the place in the code where the error
an example of what the line with an error would look like
![image](https://user-images.githubusercontent.com/6150895/168872348-0c550319-b3dc-4c32-a50c-815d8e6e6e62.png)
take a screenshot

**Comment by k-ivan** [comment]
It looks like it's in private methods. 
But if it's about them, then it couldn't work for you in earlier versions(because, private methods were already in an earlier version of the extension)

**Comment by k-ivan** [comment]
Or have you not used it in a while?

**Comment by Feans** [comment]
Until recently, your extension worked fine in my version of chrome for many years. I even wrote to you earlier [here](https://github.com/k-ivan/visual-bookmarks-chrome/issues/80). And it worked. I can't say for sure, but about two weeks ago your extension was updated and has not worked in my version of chrome since then. I have Chrome 80.0.3987.132 (stable), (32bit) for Windows OS

Fore testing purposes I just downloaded this portable developer version from here https://chromium.cypress.io/win64/stable/80.0.3987.132 and installed your latest extension and it doesn't work.

> Old versions can be found here https://www.crx4chrome.com/s.php?s=visual%20bookmarks for example.

I tried to install older version of your extension from this website but... it seem chrome doesn't allow it.

**Comment by k-ivan** [comment]
In the new version I will try to fix this, and then I will set a limit on future updates, so you will not be able to update further than this version (probably).

I'll post it here, hope it helps.

**Comment by k-ivan** [comment]
Done, version 3.26.1. Please let me know if this solved the problem.

**Comment by mario-amazing** [comment]
Hi @k-ivan, after the last update, I have this error: 
<img width="409" alt="Screenshot 2022-05-19 at 11 47 07" src="https://user-images.githubusercontent.com/9537753/169241200-a1d49961-b1c6-409e-9d45-607d9e23c2ad.png">
Extention Options couldn't be saved.

**Comment by Feans** [comment]
I just updated to 3.26.2 and problem solved!
Thank you very much :)

**Comment by k-ivan** [comment]
Great, but keep in mind that in the future the extension will not be updated to new versions.

**Comment by Feans** [comment]
> Great, but keep in mind that in the future the extension will not be updated to new versions.

Sure. That's how it should be. The main thing is to specify the correct requirements in the extension properties in extension's store, so that it is not updated in versions that do not support it.

**Comment by MadRatSRP** [comment]
I can't say for sure but it seems like i have similair problem with TS, except my screen is not just white, it shows "Folder is not found. Probably you don't have synchronised bookmarks or folder was moved/removed.
Chrome and extension's versions are the latest.

![image](https://user-images.githubusercontent.com/29717217/169380700-c49b4595-cd26-48bf-8d34-410a23a9e3e6.png)

**Comment by k-ivan** [comment]
> I can't say for sure but it seems like i have similair problem with TS, except my screen is not just white, it shows "Folder is not found. Probably you don't have synchronised bookmarks or folder was moved/removed.
> Chrome and extension's versions are the latest.
> 
> ![image](https://user-images.githubusercontent.com/29717217/169380700-c49b4595-cd26-48bf-8d34-410a23a9e3e6.png)
> 

Please reinstall the extension v3.26.2.  Unfortunately I made a mistake in version 3.26.0-1.

**Comment by k-ivan** [comment]
> Please add links for contacting
Seems to be adding links everywhere, there are both mail and github links
