### ISSUE TITLE
Thumbnails not updating to current web page

### ISSUE THREAD

**Issue by visbook** [k-ivan/visual-bookmarks-chrome#91]
Hi Ivan,
Just this morning I wanted to update about 30 thumbnails to a folder but the thumbnails are not being replaced with the latest version of the webpage, the old thumbnail reappears.
To update the thumbnails I normally click the camera icon, top left and have also tried right-click/ refresh thumbnail but neither method works, I have also tried other folders but it's the same.
When I try to update a thumbnail the purple/ blue circle appears and rotates in the thumbnail window and a new tab appears in the Windows Taskbar as though VB is trying to take a new snapshot, but it just returns the old thumbnail picture.
I have tried turning off all other chrome extensions in case they were causing the problem.

Any ideas what the issue might be?

**Comment by k-ivan** [comment]
Hi visbook

It is hard to say. Needs to be debugged in your environment (probably a bug I missed),
I checked it myself, the thumbnails are updated.

**Comment by k-ivan** [comment]
- Try to preview again, then go to the extension card in your browser settings and click on the error button if there is one. Take a screenshot of the error list.
![image](https://user-images.githubusercontent.com/6150895/170185107-f6d4229a-d43b-47c9-ae36-af76b7ac3e6a.png)

- Before you start making thumbnails, open the devtools using the `ctrl+shift+i` or `F12` keys, go to the console tab, then start updating the thumbnail and take a screenshot, after the generation is over, if something appears in the console
![image](https://user-images.githubusercontent.com/6150895/170185953-730abb0b-af81-4a62-8b5c-e414fe8cf7d4.png)

**Comment by visbook** [comment]
No "Errors" tab available, this was the Console result after updating a thumbnail-

![VB Clip](https://user-images.githubusercontent.com/87253369/170372633-6c3c9f8d-8e94-4115-9c14-9766838c1aa2.jpg)
l

**Comment by k-ivan** [comment]
Warning timeout indicates that it was not possible to make a thumbnail for the site in the allotted time. In this case, the thumbnail will not be updated. There can be many reasons, for example, a very long loading of the site.
But this is one warning, miniatures of other sites (if there are more than one) should be created.

**Comment by k-ivan** [comment]
also pay attention to this note on the options page in the modal window, if the advice from there helps, then this is the reason.
![image](https://user-images.githubusercontent.com/6150895/170419662-594e4497-e69f-4408-a727-e6c92fdae2dd.png)

**Comment by k-ivan** [comment]
Сlose at the moment, if something changes, please reopen the issue.

**Comment by visbook** [comment]
I tried the following but the Console still displayed the "Timeout waiting for a screenshot" issue
1) Extending the time on the "Delay before creating a thumbnail" slider to 5s-10s-15s
2) Uninstall VB- shut down PC- reinstall VB, that caused all the previously stored thumbnails to just now be shown as favicons, and when when selecting "refresh thumbnail" no thumbnail is created.
3) I generally use Brave Browser, so thought it might be that causing the no thumbnail issue so I created a new profile and installed VB but still not creating thumbnails.
4) I tried Edge Browser- VB works fine.

Should I uninstall/ install Brave?
Haven't tried it yet as didn't want to risk losing all my Brave settings, history, etc

**Comment by k-ivan** [comment]
Yes, it looks like a problem with the browser. 
I support Google Chrome and Microsoft Edge. Not guaranteed to work in other browsers.

**Comment by visbook** [comment]
Brave is a Chrome based browser and it's odd that VB has suddenly stopped working after 3+ years of faultless use. 
If Brave have changed something I would have no idea where to look.

I know you can't possibly test VB on every browser out there, but as Brave's user base is growing exponentially [(50 million+)](https://www.coindesk.com/business/2022/01/05/crypto-browser-brave-passes-50m-monthly-active-users/) and Edge is actually on the decline it might be beneficial for you to add Brave to the browsers VB supports and works in.

Would it be worth my while asking Brave if they have changed something major recently?

**Comment by k-ivan** [comment]
Set to check. And here is the answer

> Invalid value for bounds. Bounds must be at least 50% within visible screen space.

That is, they closed the ability to capture the screen in the background, and now it would only work if the capture window popped up in front of you. That's why I can't do anything here.

P.S. I really hope that Chrome developers do not go in the same direction, because in this case, the benefit of creating screenshots will be lost.

**Comment by visbook** [comment]
Thank you k-ivan for taking the time to further investigate this problem and finding the cause.
Do you think Brave has implemented this to stop the potential for unauthorised apps taking sneaky screenshots of for example your banking log-on screen or other privacy sensitive web pages?

It would be better if a Brave at least gave their users the option to turn this restriction off or on, or increase the Bounds to 100%.

If your brilliant extension is not allowed to work in the future in any Chrome variant it would be a terrible outcome.

**Comment by k-ivan** [comment]
Thank you for using!
I understand that permissions for the extension can scare away many people, but without them it is impossible to make this functionality. The extension does not track the user and does not send any data, and thumbnails are stored on the user's computer, it does not even have Google Analytics 😄

> Do you think Brave has implemented this to stop the potential for unauthorised apps taking sneaky in-the-background screenshots of for example your banking log-on screen or other privacy sensitive web pages?

There is nothing wrong with the screen capture itself, but they want the screen capture to be in front of you. Сertainly these rules are aimed at the high privacy and security that the Brave promotes. That is, you as a user should be aware of everything that happens.

> It would be better if a Brave at least gave their users the option to turn this restriction off or on when they ok with the risk, or increase the Bounds to 100%.

 Unfortunately I don't think they will change that.

> If your brilliant extension is not allowed to work in any future Chrome variant it would be a terrible day.

For me especially, I put a lot of time and effort into it, it will be very disappointing.

**Comment by visbook** [comment]
Hi k-ivan
As Brave now only let you take a snapshot of the page your looking at, could a possible work-around to be able update the VB thumbnails is to make the webpage requiring a new snapshot to open in front of the web page that's currently open.

When you right click a previously saved webpage in your VB folders and select "Refresh thumbnail" (see pic #1), doesn't the page have to re-open anyway to take a new snapshot, as a tab always appears in the TaskBar (see pic#2), but VB does it in the background, so you never actually see the webpage.
![Screenshot1 jpg](https://user-images.githubusercontent.com/87253369/171401081-aaf6823a-a9e3-4fad-9138-aa3fce18fa29.png)
![Screenshot2 jpg](https://user-images.githubusercontent.com/87253369/171401246-70440d1d-908c-4816-a32d-a78885b4f200.png)

**Comment by k-ivan** [comment]
Unfortunately it looks creepy. For the capture to succeed, this window must be on top of everything. That is, it will overlap part of the screen. You will always see this window and what is happening in it. And in the case of auto-generation, you will not be able to interact normally with other tabs while the generation is in progress(for example, watch YouTube at this time).

**Comment by visbook** [comment]
> you will not be able to interact normally with other tabs while the generation is in progress

I think that would be okay though as it would only take 1-2 seconds (depending on the time chosen in "delay before creating a thumbnail" in VB's options).
When I want to update the VB thumbnails to their latest versions it's normally because I'm doing work connected to that subject folder and not doing casual web browsing/ YouTubing at the same time, so it would be beneficial to see the webpage/ thumbnail I want updating at full size for a short period.

**Comment by k-ivan** [comment]
Well, that's all, it turns out Brave was updated a little earlier, this change is now in Сhrome(v102). Unfortunately, this seems to be the end of the application.

**Comment by k-ivan** [comment]
I'll try to add a window on top, otherwise the extension will stall. It's hard to say what will come of it.

**Comment by k-ivan** [comment]
This is definitely sad 😟. But I have a second extension that I will develop )
As for the bookmarks, I'll make the screen capture popup visible, it certainly affects the user experience, but it won't keep this feature.

**Comment by k-ivan** [comment]
Hi @visbook !

I updated the extension to version 4, now the capture is in the foreground, if it's still relevant, try version 4.

**Comment by visbook** [comment]
Hi k-ivan,
That's brilliant if you have got VB to work again.
How do you update to version 4 as I've tried to do it through "settings > extensions > manage extensions > Update" but VB doesn't update from 3.26.2.

**Comment by k-ivan** [comment]
Still under review in the extension store

**Comment by visbook** [comment]
Hi k-ivan, you're a genius!

Works better then ever and I am so grateful VB can continue on.
Is there a way to make a small donation to say thanks for your continued work on the VB project?

**Comment by k-ivan** [comment]
Great, glad it's working again.

> Is there a way to make a small donation to say thanks for your continued work on the VB project?

Thank you. Not yet, maybe later I will add some link.

**Comment by visbook** [comment]
I did have a suggestion that would make it quicker to delete no longer needed thumbnails-
Is it possible to put an **X** or the dustbin icon in the right hand corner of each thumbnail (or under the existing circle with 3 dots if that is easier, as I quite often have to delete 30-40 thumbnails in one go and it would half the amount of mouse clicks if the "Remove/ dustbin" was at the top level.

Thanks

**Comment by k-ivan** [comment]
Done, added to the context menu item in v4.2.0
![image](https://user-images.githubusercontent.com/6150895/173305105-35f6a955-176a-4b05-b416-9f3adeb6b7eb.png)

**Comment by k-ivan** [comment]
I'm sorry, but I'm not ready to add a separate button for this issue.
