### ISSUE TITLE
The last update removed all thumbnails

### ISSUE THREAD

**Issue by Feans** [k-ivan/visual-bookmarks-chrome#92]
Последнее обновление удалило все миниатюры. Кроме того мы в прошлый раз с вами говорили что расширение не должно обновляться для старых версий хрома, но оно почему-то обновилось.

Вторая проблема - при обновлении миниатюр сплывает окно с сайтом для которого происходит обновление, что мешает работе. Раньше все миниатюры обновлялись в фоновом окне.

eng:
The last update removed all thumbnails. In addition, last time we talked with you that the extension should not be updated for older versions of chrome, but for some reason it has been updated.

The second problem is that when updating thumbnails, a window pops up with the site for which the update is taking place, which interferes with the work. Previously, all thumbnails were updated in the background window.

**Comment by k-ivan** [comment]
Там есть процесс переноса, по какой-то причине он не происходит у вас, к сожалению, я не могу определить по какой. Возможно что-то блокирует браузер, возможно антивирус, кроме Вас есть другие люди столкнувшиеся с отсутствием переноса миниатюр. Я проверял на двух разных устройствах более 600 миниатюр, и процесс переноса успешно переносил их все. Сложно судить, почему в каких-то случаях он не завершается. А по поводу обновлений я не совсем понял, я с тех пор пока что не выкатывал каких-то новых фич, у которых поддержка только зеленых браузеров. То есть чуть позже собирался, но пока все фичи, должны поддерживаться и в вашей версии.

По поводу попапа с захватом поверх всех окон, это не проблема, теперь только так возможен захват экрана, начиная с новых версий движка бразуера захват изображения из фона не возможен.

**Comment by Feans** [comment]
Ну с миниатюрами то ладно, их можно обновить. А вот то, что захват изображения из фона не возможен, это не очень приятная новость. Вот поэтому, это одна из причин, по которым я и не обновляю браузер, по крайней мере слишком часто, т.к. постоянно что-то в расширениях отваливается или они сами перестают работать в новых версиях. Без обновления расширения у меня и других бы все работало на старом хроме, а теперь вот окошко будет всплывать ненужное при создании миниатюр, придется откатываться на старую версию и отвязывать её от обновлений.

**Comment by k-ivan** [comment]
Закручивание гаек конфиденциальности разработчиками началось давно. И вот они все-таки добрались до захвата экрана. Теперь только так, это конечно портит UX пользователя, но ничего не поделать, по сути и раньше это было своего рода хаком(то есть я к тому что они не рассчитывали, что пользоваться будут таким способом).

**Comment by Feans** [comment]
Ну понятно, просто т.к. в старом браузере можно всё без окошек делать, обновление по сути привело к ухудшению, т.е. можно было сделать чтоб в старых версиях расширение не обновлялось. В принципе всё, что я хотел сказать.

**Comment by k-ivan** [comment]
Я понимаю, что Вы имейте ввиду, но версия ограничивают только тогда, когда хотят использовать новую технологию, которая не будет работать в старых версиях.

**Comment by k-ivan** [comment]
Интересно конечно, получается их уже не было, либо доступ к ним по каким то причинам чем-то блокируется. Это очень странно, на двух машинах проверял огромное кол-во миниатюр и все перенеслось. А вы используете антивирус?

В любом случае, запустите генерацию ещё раз, новые скрины делаются в большем размере и гораздо чётче старых, а весят меньше.

**Comment by Feans** [comment]
> А вы используете антивирус?
Да, Nod32, но он никаких уведомлений от него не было.

Я еще использую google chrome от платформы Portableapps, может поэтому, а может из-за старой версии.
А может потому что миниатюр было довольно много, 2-3 тысячи. Обновлять их все не в фоне, как раньше конечно будет не комильфо :)

**Comment by k-ivan** [comment]
> Я еще использую google chrome от платформы Portableapps, может поэтому, а может из-за старой версии.
А может потому что миниатюр было довольно много, 2-3 тысячи.

Да яснее не стало ). Поскольку не только у Вас такое наблюдается, все описанные причины могут иметь место. 
Хотя в чуть меньшей степени я бы думал на общее кол-во(так как там такая же операция как и в отображении, а ведь такое- кол-во не мешало работать расширению). 

> Может можно как-то вынести окно, где делается скриншот далеко за пределы видимого экрана, чтобы оно не мешалось при работе?

Увы нет, теперь это обязательное требование, если окно спрятать от пользователя, апи браузера не будет захватывать экран(безопасность и конфиденциальность и все такое).
