### ISSUE TITLE
Ставить focus на "ок" в модалке удаления закладки

### ISSUE THREAD

**Issue by notiv-nt** [k-ivan/visual-bookmarks-chrome#95]
![image](https://user-images.githubusercontent.com/10743009/174030950-b80c5e75-4ac8-474f-a780-43bbdf8fd2b4.png)

Для удобства было бы классно ставить фокус на кнопку подтверждения при открытии.

Где-нибудь после этой строки

https://github.com/k-ivan/visual-bookmarks-chrome/blob/e2ac795a198589c60e4becd1133699fcdc57ea84/src/js/plugins/confirmPopup.js#L46

**Comment by k-ivan** [comment]
Появится в ближайшем обновлении.
